// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/dailycheckinclaim"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DailyCheckInClaim is the model entity for the DailyCheckInClaim schema.
type DailyCheckInClaim struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ActivityStartAt holds the value of the "activity_start_at" field.
	ActivityStartAt time.Time `json:"activity_start_at,omitempty"`
	// CheckInDate holds the value of the "check_in_date" field.
	CheckInDate time.Time `json:"check_in_date,omitempty"`
	// RewardAmount holds the value of the "reward_amount" field.
	RewardAmount float64 `json:"reward_amount,omitempty"`
	// BalanceAfter holds the value of the "balance_after" field.
	BalanceAfter float64 `json:"balance_after,omitempty"`
	// ClaimedAt holds the value of the "claimed_at" field.
	ClaimedAt time.Time `json:"claimed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DailyCheckInClaimQuery when eager-loading is set.
	Edges        DailyCheckInClaimEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DailyCheckInClaimEdges holds the relations/edges for other nodes in the graph.
type DailyCheckInClaimEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DailyCheckInClaimEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DailyCheckInClaim) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dailycheckinclaim.FieldRewardAmount, dailycheckinclaim.FieldBalanceAfter:
			values[i] = new(sql.NullFloat64)
		case dailycheckinclaim.FieldID, dailycheckinclaim.FieldUserID:
			values[i] = new(sql.NullInt64)
		case dailycheckinclaim.FieldActivityStartAt, dailycheckinclaim.FieldCheckInDate, dailycheckinclaim.FieldClaimedAt, dailycheckinclaim.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DailyCheckInClaim fields.
func (_m *DailyCheckInClaim) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dailycheckinclaim.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case dailycheckinclaim.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case dailycheckinclaim.FieldActivityStartAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field activity_start_at", values[i])
			} else if value.Valid {
				_m.ActivityStartAt = value.Time
			}
		case dailycheckinclaim.FieldCheckInDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field check_in_date", values[i])
			} else if value.Valid {
				_m.CheckInDate = value.Time
			}
		case dailycheckinclaim.FieldRewardAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_amount", values[i])
			} else if value.Valid {
				_m.RewardAmount = value.Float64
			}
		case dailycheckinclaim.FieldBalanceAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after", values[i])
			} else if value.Valid {
				_m.BalanceAfter = value.Float64
			}
		case dailycheckinclaim.FieldClaimedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field claimed_at", values[i])
			} else if value.Valid {
				_m.ClaimedAt = value.Time
			}
		case dailycheckinclaim.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DailyCheckInClaim.
// This includes values selected through modifiers, order, etc.
func (_m *DailyCheckInClaim) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the DailyCheckInClaim entity.
func (_m *DailyCheckInClaim) QueryUser() *UserQuery {
	return NewDailyCheckInClaimClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this DailyCheckInClaim.
// Note that you need to call DailyCheckInClaim.Unwrap() before calling this method if this DailyCheckInClaim
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DailyCheckInClaim) Update() *DailyCheckInClaimUpdateOne {
	return NewDailyCheckInClaimClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DailyCheckInClaim entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DailyCheckInClaim) Unwrap() *DailyCheckInClaim {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DailyCheckInClaim is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DailyCheckInClaim) String() string {
	var builder strings.Builder
	builder.WriteString("DailyCheckInClaim(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("activity_start_at=")
	builder.WriteString(_m.ActivityStartAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("check_in_date=")
	builder.WriteString(_m.CheckInDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("reward_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardAmount))
	builder.WriteString(", ")
	builder.WriteString("balance_after=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceAfter))
	builder.WriteString(", ")
	builder.WriteString("claimed_at=")
	builder.WriteString(_m.ClaimedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DailyCheckInClaims is a parsable slice of DailyCheckInClaim.
type DailyCheckInClaims []*DailyCheckInClaim
