// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/dailycheckinclaim"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// DailyCheckInClaimDelete is the builder for deleting a DailyCheckInClaim entity.
type DailyCheckInClaimDelete struct {
	config
	hooks    []Hook
	mutation *DailyCheckInClaimMutation
}

// Where appends a list predicates to the DailyCheckInClaimDelete builder.
func (_d *DailyCheckInClaimDelete) Where(ps ...predicate.DailyCheckInClaim) *DailyCheckInClaimDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DailyCheckInClaimDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DailyCheckInClaimDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DailyCheckInClaimDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dailycheckinclaim.Table, sqlgraph.NewFieldSpec(dailycheckinclaim.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DailyCheckInClaimDeleteOne is the builder for deleting a single DailyCheckInClaim entity.
type DailyCheckInClaimDeleteOne struct {
	_d *DailyCheckInClaimDelete
}

// Where appends a list predicates to the DailyCheckInClaimDelete builder.
func (_d *DailyCheckInClaimDeleteOne) Where(ps ...predicate.DailyCheckInClaim) *DailyCheckInClaimDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DailyCheckInClaimDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dailycheckinclaim.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DailyCheckInClaimDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
