// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/dailycheckinclaim"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DailyCheckInClaimUpdate is the builder for updating DailyCheckInClaim entities.
type DailyCheckInClaimUpdate struct {
	config
	hooks    []Hook
	mutation *DailyCheckInClaimMutation
}

// Where appends a list predicates to the DailyCheckInClaimUpdate builder.
func (_u *DailyCheckInClaimUpdate) Where(ps ...predicate.DailyCheckInClaim) *DailyCheckInClaimUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DailyCheckInClaimUpdate) SetUserID(v int64) *DailyCheckInClaimUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DailyCheckInClaimUpdate) SetNillableUserID(v *int64) *DailyCheckInClaimUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetActivityStartAt sets the "activity_start_at" field.
func (_u *DailyCheckInClaimUpdate) SetActivityStartAt(v time.Time) *DailyCheckInClaimUpdate {
	_u.mutation.SetActivityStartAt(v)
	return _u
}

// SetNillableActivityStartAt sets the "activity_start_at" field if the given value is not nil.
func (_u *DailyCheckInClaimUpdate) SetNillableActivityStartAt(v *time.Time) *DailyCheckInClaimUpdate {
	if v != nil {
		_u.SetActivityStartAt(*v)
	}
	return _u
}

// SetCheckInDate sets the "check_in_date" field.
func (_u *DailyCheckInClaimUpdate) SetCheckInDate(v time.Time) *DailyCheckInClaimUpdate {
	_u.mutation.SetCheckInDate(v)
	return _u
}

// SetNillableCheckInDate sets the "check_in_date" field if the given value is not nil.
func (_u *DailyCheckInClaimUpdate) SetNillableCheckInDate(v *time.Time) *DailyCheckInClaimUpdate {
	if v != nil {
		_u.SetCheckInDate(*v)
	}
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *DailyCheckInClaimUpdate) SetRewardAmount(v float64) *DailyCheckInClaimUpdate {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *DailyCheckInClaimUpdate) SetNillableRewardAmount(v *float64) *DailyCheckInClaimUpdate {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *DailyCheckInClaimUpdate) AddRewardAmount(v float64) *DailyCheckInClaimUpdate {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *DailyCheckInClaimUpdate) SetBalanceAfter(v float64) *DailyCheckInClaimUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *DailyCheckInClaimUpdate) SetNillableBalanceAfter(v *float64) *DailyCheckInClaimUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *DailyCheckInClaimUpdate) AddBalanceAfter(v float64) *DailyCheckInClaimUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *DailyCheckInClaimUpdate) SetClaimedAt(v time.Time) *DailyCheckInClaimUpdate {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *DailyCheckInClaimUpdate) SetNillableClaimedAt(v *time.Time) *DailyCheckInClaimUpdate {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DailyCheckInClaimUpdate) SetUser(v *User) *DailyCheckInClaimUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the DailyCheckInClaimMutation object of the builder.
func (_u *DailyCheckInClaimUpdate) Mutation() *DailyCheckInClaimMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DailyCheckInClaimUpdate) ClearUser() *DailyCheckInClaimUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DailyCheckInClaimUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyCheckInClaimUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DailyCheckInClaimUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyCheckInClaimUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DailyCheckInClaimUpdate) check() error {
	if v, ok := _u.mutation.RewardAmount(); ok {
		if err := dailycheckinclaim.RewardAmountValidator(v); err != nil {
			return &ValidationError{Name: "reward_amount", err: fmt.Errorf(`ent: validator failed for field "DailyCheckInClaim.reward_amount": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DailyCheckInClaim.user"`)
	}
	return nil
}

func (_u *DailyCheckInClaimUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dailycheckinclaim.Table, dailycheckinclaim.Columns, sqlgraph.NewFieldSpec(dailycheckinclaim.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActivityStartAt(); ok {
		_spec.SetField(dailycheckinclaim.FieldActivityStartAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CheckInDate(); ok {
		_spec.SetField(dailycheckinclaim.FieldCheckInDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(dailycheckinclaim.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(dailycheckinclaim.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(dailycheckinclaim.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(dailycheckinclaim.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(dailycheckinclaim.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailycheckinclaim.UserTable,
			Columns: []string{dailycheckinclaim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailycheckinclaim.UserTable,
			Columns: []string{dailycheckinclaim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailycheckinclaim.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DailyCheckInClaimUpdateOne is the builder for updating a single DailyCheckInClaim entity.
type DailyCheckInClaimUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DailyCheckInClaimMutation
}

// SetUserID sets the "user_id" field.
func (_u *DailyCheckInClaimUpdateOne) SetUserID(v int64) *DailyCheckInClaimUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DailyCheckInClaimUpdateOne) SetNillableUserID(v *int64) *DailyCheckInClaimUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetActivityStartAt sets the "activity_start_at" field.
func (_u *DailyCheckInClaimUpdateOne) SetActivityStartAt(v time.Time) *DailyCheckInClaimUpdateOne {
	_u.mutation.SetActivityStartAt(v)
	return _u
}

// SetNillableActivityStartAt sets the "activity_start_at" field if the given value is not nil.
func (_u *DailyCheckInClaimUpdateOne) SetNillableActivityStartAt(v *time.Time) *DailyCheckInClaimUpdateOne {
	if v != nil {
		_u.SetActivityStartAt(*v)
	}
	return _u
}

// SetCheckInDate sets the "check_in_date" field.
func (_u *DailyCheckInClaimUpdateOne) SetCheckInDate(v time.Time) *DailyCheckInClaimUpdateOne {
	_u.mutation.SetCheckInDate(v)
	return _u
}

// SetNillableCheckInDate sets the "check_in_date" field if the given value is not nil.
func (_u *DailyCheckInClaimUpdateOne) SetNillableCheckInDate(v *time.Time) *DailyCheckInClaimUpdateOne {
	if v != nil {
		_u.SetCheckInDate(*v)
	}
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *DailyCheckInClaimUpdateOne) SetRewardAmount(v float64) *DailyCheckInClaimUpdateOne {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *DailyCheckInClaimUpdateOne) SetNillableRewardAmount(v *float64) *DailyCheckInClaimUpdateOne {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *DailyCheckInClaimUpdateOne) AddRewardAmount(v float64) *DailyCheckInClaimUpdateOne {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *DailyCheckInClaimUpdateOne) SetBalanceAfter(v float64) *DailyCheckInClaimUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *DailyCheckInClaimUpdateOne) SetNillableBalanceAfter(v *float64) *DailyCheckInClaimUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *DailyCheckInClaimUpdateOne) AddBalanceAfter(v float64) *DailyCheckInClaimUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *DailyCheckInClaimUpdateOne) SetClaimedAt(v time.Time) *DailyCheckInClaimUpdateOne {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *DailyCheckInClaimUpdateOne) SetNillableClaimedAt(v *time.Time) *DailyCheckInClaimUpdateOne {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DailyCheckInClaimUpdateOne) SetUser(v *User) *DailyCheckInClaimUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the DailyCheckInClaimMutation object of the builder.
func (_u *DailyCheckInClaimUpdateOne) Mutation() *DailyCheckInClaimMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DailyCheckInClaimUpdateOne) ClearUser() *DailyCheckInClaimUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the DailyCheckInClaimUpdate builder.
func (_u *DailyCheckInClaimUpdateOne) Where(ps ...predicate.DailyCheckInClaim) *DailyCheckInClaimUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DailyCheckInClaimUpdateOne) Select(field string, fields ...string) *DailyCheckInClaimUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DailyCheckInClaim entity.
func (_u *DailyCheckInClaimUpdateOne) Save(ctx context.Context) (*DailyCheckInClaim, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyCheckInClaimUpdateOne) SaveX(ctx context.Context) *DailyCheckInClaim {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DailyCheckInClaimUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyCheckInClaimUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DailyCheckInClaimUpdateOne) check() error {
	if v, ok := _u.mutation.RewardAmount(); ok {
		if err := dailycheckinclaim.RewardAmountValidator(v); err != nil {
			return &ValidationError{Name: "reward_amount", err: fmt.Errorf(`ent: validator failed for field "DailyCheckInClaim.reward_amount": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DailyCheckInClaim.user"`)
	}
	return nil
}

func (_u *DailyCheckInClaimUpdateOne) sqlSave(ctx context.Context) (_node *DailyCheckInClaim, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dailycheckinclaim.Table, dailycheckinclaim.Columns, sqlgraph.NewFieldSpec(dailycheckinclaim.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DailyCheckInClaim.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dailycheckinclaim.FieldID)
		for _, f := range fields {
			if !dailycheckinclaim.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dailycheckinclaim.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActivityStartAt(); ok {
		_spec.SetField(dailycheckinclaim.FieldActivityStartAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CheckInDate(); ok {
		_spec.SetField(dailycheckinclaim.FieldCheckInDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(dailycheckinclaim.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(dailycheckinclaim.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(dailycheckinclaim.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(dailycheckinclaim.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(dailycheckinclaim.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailycheckinclaim.UserTable,
			Columns: []string{dailycheckinclaim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailycheckinclaim.UserTable,
			Columns: []string{dailycheckinclaim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DailyCheckInClaim{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailycheckinclaim.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
