// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userapikeyroute"
)

// UserAPIKeyRouteUpdate is the builder for updating UserAPIKeyRoute entities.
type UserAPIKeyRouteUpdate struct {
	config
	hooks    []Hook
	mutation *UserAPIKeyRouteMutation
}

// Where appends a list predicates to the UserAPIKeyRouteUpdate builder.
func (_u *UserAPIKeyRouteUpdate) Where(ps ...predicate.UserAPIKeyRoute) *UserAPIKeyRouteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAPIKeyRouteUpdate) SetUpdatedAt(v time.Time) *UserAPIKeyRouteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserAPIKeyRouteUpdate) SetUserID(v int64) *UserAPIKeyRouteUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAPIKeyRouteUpdate) SetNillableUserID(v *int64) *UserAPIKeyRouteUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetKeyType sets the "key_type" field.
func (_u *UserAPIKeyRouteUpdate) SetKeyType(v string) *UserAPIKeyRouteUpdate {
	_u.mutation.SetKeyType(v)
	return _u
}

// SetNillableKeyType sets the "key_type" field if the given value is not nil.
func (_u *UserAPIKeyRouteUpdate) SetNillableKeyType(v *string) *UserAPIKeyRouteUpdate {
	if v != nil {
		_u.SetKeyType(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserAPIKeyRouteUpdate) SetGroupID(v int64) *UserAPIKeyRouteUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserAPIKeyRouteUpdate) SetNillableGroupID(v *int64) *UserAPIKeyRouteUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserAPIKeyRouteUpdate) SetUser(v *User) *UserAPIKeyRouteUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *UserAPIKeyRouteUpdate) SetGroup(v *Group) *UserAPIKeyRouteUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the UserAPIKeyRouteMutation object of the builder.
func (_u *UserAPIKeyRouteUpdate) Mutation() *UserAPIKeyRouteMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserAPIKeyRouteUpdate) ClearUser() *UserAPIKeyRouteUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *UserAPIKeyRouteUpdate) ClearGroup() *UserAPIKeyRouteUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAPIKeyRouteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAPIKeyRouteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAPIKeyRouteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAPIKeyRouteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAPIKeyRouteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userapikeyroute.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAPIKeyRouteUpdate) check() error {
	if v, ok := _u.mutation.KeyType(); ok {
		if err := userapikeyroute.KeyTypeValidator(v); err != nil {
			return &ValidationError{Name: "key_type", err: fmt.Errorf(`ent: validator failed for field "UserAPIKeyRoute.key_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAPIKeyRoute.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAPIKeyRoute.group"`)
	}
	return nil
}

func (_u *UserAPIKeyRouteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userapikeyroute.Table, userapikeyroute.Columns, sqlgraph.NewFieldSpec(userapikeyroute.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userapikeyroute.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.KeyType(); ok {
		_spec.SetField(userapikeyroute.FieldKeyType, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userapikeyroute.UserTable,
			Columns: []string{userapikeyroute.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userapikeyroute.UserTable,
			Columns: []string{userapikeyroute.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userapikeyroute.GroupTable,
			Columns: []string{userapikeyroute.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userapikeyroute.GroupTable,
			Columns: []string{userapikeyroute.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userapikeyroute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAPIKeyRouteUpdateOne is the builder for updating a single UserAPIKeyRoute entity.
type UserAPIKeyRouteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAPIKeyRouteMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAPIKeyRouteUpdateOne) SetUpdatedAt(v time.Time) *UserAPIKeyRouteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserAPIKeyRouteUpdateOne) SetUserID(v int64) *UserAPIKeyRouteUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAPIKeyRouteUpdateOne) SetNillableUserID(v *int64) *UserAPIKeyRouteUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetKeyType sets the "key_type" field.
func (_u *UserAPIKeyRouteUpdateOne) SetKeyType(v string) *UserAPIKeyRouteUpdateOne {
	_u.mutation.SetKeyType(v)
	return _u
}

// SetNillableKeyType sets the "key_type" field if the given value is not nil.
func (_u *UserAPIKeyRouteUpdateOne) SetNillableKeyType(v *string) *UserAPIKeyRouteUpdateOne {
	if v != nil {
		_u.SetKeyType(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserAPIKeyRouteUpdateOne) SetGroupID(v int64) *UserAPIKeyRouteUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserAPIKeyRouteUpdateOne) SetNillableGroupID(v *int64) *UserAPIKeyRouteUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserAPIKeyRouteUpdateOne) SetUser(v *User) *UserAPIKeyRouteUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *UserAPIKeyRouteUpdateOne) SetGroup(v *Group) *UserAPIKeyRouteUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the UserAPIKeyRouteMutation object of the builder.
func (_u *UserAPIKeyRouteUpdateOne) Mutation() *UserAPIKeyRouteMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserAPIKeyRouteUpdateOne) ClearUser() *UserAPIKeyRouteUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *UserAPIKeyRouteUpdateOne) ClearGroup() *UserAPIKeyRouteUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the UserAPIKeyRouteUpdate builder.
func (_u *UserAPIKeyRouteUpdateOne) Where(ps ...predicate.UserAPIKeyRoute) *UserAPIKeyRouteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAPIKeyRouteUpdateOne) Select(field string, fields ...string) *UserAPIKeyRouteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserAPIKeyRoute entity.
func (_u *UserAPIKeyRouteUpdateOne) Save(ctx context.Context) (*UserAPIKeyRoute, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAPIKeyRouteUpdateOne) SaveX(ctx context.Context) *UserAPIKeyRoute {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAPIKeyRouteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAPIKeyRouteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAPIKeyRouteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userapikeyroute.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAPIKeyRouteUpdateOne) check() error {
	if v, ok := _u.mutation.KeyType(); ok {
		if err := userapikeyroute.KeyTypeValidator(v); err != nil {
			return &ValidationError{Name: "key_type", err: fmt.Errorf(`ent: validator failed for field "UserAPIKeyRoute.key_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAPIKeyRoute.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAPIKeyRoute.group"`)
	}
	return nil
}

func (_u *UserAPIKeyRouteUpdateOne) sqlSave(ctx context.Context) (_node *UserAPIKeyRoute, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userapikeyroute.Table, userapikeyroute.Columns, sqlgraph.NewFieldSpec(userapikeyroute.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAPIKeyRoute.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userapikeyroute.FieldID)
		for _, f := range fields {
			if !userapikeyroute.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userapikeyroute.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userapikeyroute.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.KeyType(); ok {
		_spec.SetField(userapikeyroute.FieldKeyType, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userapikeyroute.UserTable,
			Columns: []string{userapikeyroute.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userapikeyroute.UserTable,
			Columns: []string{userapikeyroute.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userapikeyroute.GroupTable,
			Columns: []string{userapikeyroute.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userapikeyroute.GroupTable,
			Columns: []string{userapikeyroute.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserAPIKeyRoute{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userapikeyroute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
