// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/webchatattachment"
)

// WebChatAttachmentCreate is the builder for creating a WebChatAttachment entity.
type WebChatAttachmentCreate struct {
	config
	mutation *WebChatAttachmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMessageID sets the "message_id" field.
func (_c *WebChatAttachmentCreate) SetMessageID(v int64) *WebChatAttachmentCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_c *WebChatAttachmentCreate) SetNillableMessageID(v *int64) *WebChatAttachmentCreate {
	if v != nil {
		_c.SetMessageID(*v)
	}
	return _c
}

// SetConversationID sets the "conversation_id" field.
func (_c *WebChatAttachmentCreate) SetConversationID(v int64) *WebChatAttachmentCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_c *WebChatAttachmentCreate) SetNillableConversationID(v *int64) *WebChatAttachmentCreate {
	if v != nil {
		_c.SetConversationID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *WebChatAttachmentCreate) SetUserID(v int64) *WebChatAttachmentCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *WebChatAttachmentCreate) SetKind(v string) *WebChatAttachmentCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetFilename sets the "filename" field.
func (_c *WebChatAttachmentCreate) SetFilename(v string) *WebChatAttachmentCreate {
	_c.mutation.SetFilename(v)
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *WebChatAttachmentCreate) SetContentType(v string) *WebChatAttachmentCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *WebChatAttachmentCreate) SetSizeBytes(v int64) *WebChatAttachmentCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetStorageKey sets the "storage_key" field.
func (_c *WebChatAttachmentCreate) SetStorageKey(v string) *WebChatAttachmentCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *WebChatAttachmentCreate) SetSha256(v string) *WebChatAttachmentCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetTextPreview sets the "text_preview" field.
func (_c *WebChatAttachmentCreate) SetTextPreview(v string) *WebChatAttachmentCreate {
	_c.mutation.SetTextPreview(v)
	return _c
}

// SetNillableTextPreview sets the "text_preview" field if the given value is not nil.
func (_c *WebChatAttachmentCreate) SetNillableTextPreview(v *string) *WebChatAttachmentCreate {
	if v != nil {
		_c.SetTextPreview(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *WebChatAttachmentCreate) SetStatus(v string) *WebChatAttachmentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WebChatAttachmentCreate) SetNillableStatus(v *string) *WebChatAttachmentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WebChatAttachmentCreate) SetCreatedAt(v time.Time) *WebChatAttachmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WebChatAttachmentCreate) SetNillableCreatedAt(v *time.Time) *WebChatAttachmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the WebChatAttachmentMutation object of the builder.
func (_c *WebChatAttachmentCreate) Mutation() *WebChatAttachmentMutation {
	return _c.mutation
}

// Save creates the WebChatAttachment in the database.
func (_c *WebChatAttachmentCreate) Save(ctx context.Context) (*WebChatAttachment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WebChatAttachmentCreate) SaveX(ctx context.Context) *WebChatAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebChatAttachmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebChatAttachmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WebChatAttachmentCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := webchatattachment.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := webchatattachment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WebChatAttachmentCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "WebChatAttachment.user_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "WebChatAttachment.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := webchatattachment.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "WebChatAttachment.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Filename(); !ok {
		return &ValidationError{Name: "filename", err: errors.New(`ent: missing required field "WebChatAttachment.filename"`)}
	}
	if v, ok := _c.mutation.Filename(); ok {
		if err := webchatattachment.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "WebChatAttachment.filename": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "WebChatAttachment.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := webchatattachment.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "WebChatAttachment.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "WebChatAttachment.size_bytes"`)}
	}
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "WebChatAttachment.storage_key"`)}
	}
	if v, ok := _c.mutation.StorageKey(); ok {
		if err := webchatattachment.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "WebChatAttachment.storage_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`ent: missing required field "WebChatAttachment.sha256"`)}
	}
	if v, ok := _c.mutation.Sha256(); ok {
		if err := webchatattachment.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "WebChatAttachment.sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WebChatAttachment.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := webchatattachment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WebChatAttachment.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WebChatAttachment.created_at"`)}
	}
	return nil
}

func (_c *WebChatAttachmentCreate) sqlSave(ctx context.Context) (*WebChatAttachment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WebChatAttachmentCreate) createSpec() (*WebChatAttachment, *sqlgraph.CreateSpec) {
	var (
		_node = &WebChatAttachment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(webchatattachment.Table, sqlgraph.NewFieldSpec(webchatattachment.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(webchatattachment.FieldMessageID, field.TypeInt64, value)
		_node.MessageID = &value
	}
	if value, ok := _c.mutation.ConversationID(); ok {
		_spec.SetField(webchatattachment.FieldConversationID, field.TypeInt64, value)
		_node.ConversationID = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(webchatattachment.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(webchatattachment.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Filename(); ok {
		_spec.SetField(webchatattachment.FieldFilename, field.TypeString, value)
		_node.Filename = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(webchatattachment.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(webchatattachment.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(webchatattachment.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(webchatattachment.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	if value, ok := _c.mutation.TextPreview(); ok {
		_spec.SetField(webchatattachment.FieldTextPreview, field.TypeString, value)
		_node.TextPreview = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(webchatattachment.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(webchatattachment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WebChatAttachment.Create().
//		SetMessageID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebChatAttachmentUpsert) {
//			SetMessageID(v+v).
//		}).
//		Exec(ctx)
func (_c *WebChatAttachmentCreate) OnConflict(opts ...sql.ConflictOption) *WebChatAttachmentUpsertOne {
	_c.conflict = opts
	return &WebChatAttachmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WebChatAttachment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WebChatAttachmentCreate) OnConflictColumns(columns ...string) *WebChatAttachmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WebChatAttachmentUpsertOne{
		create: _c,
	}
}

type (
	// WebChatAttachmentUpsertOne is the builder for "upsert"-ing
	//  one WebChatAttachment node.
	WebChatAttachmentUpsertOne struct {
		create *WebChatAttachmentCreate
	}

	// WebChatAttachmentUpsert is the "OnConflict" setter.
	WebChatAttachmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetMessageID sets the "message_id" field.
func (u *WebChatAttachmentUpsert) SetMessageID(v int64) *WebChatAttachmentUpsert {
	u.Set(webchatattachment.FieldMessageID, v)
	return u
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *WebChatAttachmentUpsert) UpdateMessageID() *WebChatAttachmentUpsert {
	u.SetExcluded(webchatattachment.FieldMessageID)
	return u
}

// AddMessageID adds v to the "message_id" field.
func (u *WebChatAttachmentUpsert) AddMessageID(v int64) *WebChatAttachmentUpsert {
	u.Add(webchatattachment.FieldMessageID, v)
	return u
}

// ClearMessageID clears the value of the "message_id" field.
func (u *WebChatAttachmentUpsert) ClearMessageID() *WebChatAttachmentUpsert {
	u.SetNull(webchatattachment.FieldMessageID)
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *WebChatAttachmentUpsert) SetConversationID(v int64) *WebChatAttachmentUpsert {
	u.Set(webchatattachment.FieldConversationID, v)
	return u
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *WebChatAttachmentUpsert) UpdateConversationID() *WebChatAttachmentUpsert {
	u.SetExcluded(webchatattachment.FieldConversationID)
	return u
}

// AddConversationID adds v to the "conversation_id" field.
func (u *WebChatAttachmentUpsert) AddConversationID(v int64) *WebChatAttachmentUpsert {
	u.Add(webchatattachment.FieldConversationID, v)
	return u
}

// ClearConversationID clears the value of the "conversation_id" field.
func (u *WebChatAttachmentUpsert) ClearConversationID() *WebChatAttachmentUpsert {
	u.SetNull(webchatattachment.FieldConversationID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *WebChatAttachmentUpsert) SetUserID(v int64) *WebChatAttachmentUpsert {
	u.Set(webchatattachment.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WebChatAttachmentUpsert) UpdateUserID() *WebChatAttachmentUpsert {
	u.SetExcluded(webchatattachment.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *WebChatAttachmentUpsert) AddUserID(v int64) *WebChatAttachmentUpsert {
	u.Add(webchatattachment.FieldUserID, v)
	return u
}

// SetKind sets the "kind" field.
func (u *WebChatAttachmentUpsert) SetKind(v string) *WebChatAttachmentUpsert {
	u.Set(webchatattachment.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *WebChatAttachmentUpsert) UpdateKind() *WebChatAttachmentUpsert {
	u.SetExcluded(webchatattachment.FieldKind)
	return u
}

// SetFilename sets the "filename" field.
func (u *WebChatAttachmentUpsert) SetFilename(v string) *WebChatAttachmentUpsert {
	u.Set(webchatattachment.FieldFilename, v)
	return u
}

// UpdateFilename sets the "filename" field to the value that was provided on create.
func (u *WebChatAttachmentUpsert) UpdateFilename() *WebChatAttachmentUpsert {
	u.SetExcluded(webchatattachment.FieldFilename)
	return u
}

// SetContentType sets the "content_type" field.
func (u *WebChatAttachmentUpsert) SetContentType(v string) *WebChatAttachmentUpsert {
	u.Set(webchatattachment.FieldContentType, v)
	return u
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *WebChatAttachmentUpsert) UpdateContentType() *WebChatAttachmentUpsert {
	u.SetExcluded(webchatattachment.FieldContentType)
	return u
}

// SetSizeBytes sets the "size_bytes" field.
func (u *WebChatAttachmentUpsert) SetSizeBytes(v int64) *WebChatAttachmentUpsert {
	u.Set(webchatattachment.FieldSizeBytes, v)
	return u
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *WebChatAttachmentUpsert) UpdateSizeBytes() *WebChatAttachmentUpsert {
	u.SetExcluded(webchatattachment.FieldSizeBytes)
	return u
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *WebChatAttachmentUpsert) AddSizeBytes(v int64) *WebChatAttachmentUpsert {
	u.Add(webchatattachment.FieldSizeBytes, v)
	return u
}

// SetStorageKey sets the "storage_key" field.
func (u *WebChatAttachmentUpsert) SetStorageKey(v string) *WebChatAttachmentUpsert {
	u.Set(webchatattachment.FieldStorageKey, v)
	return u
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *WebChatAttachmentUpsert) UpdateStorageKey() *WebChatAttachmentUpsert {
	u.SetExcluded(webchatattachment.FieldStorageKey)
	return u
}

// SetSha256 sets the "sha256" field.
func (u *WebChatAttachmentUpsert) SetSha256(v string) *WebChatAttachmentUpsert {
	u.Set(webchatattachment.FieldSha256, v)
	return u
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *WebChatAttachmentUpsert) UpdateSha256() *WebChatAttachmentUpsert {
	u.SetExcluded(webchatattachment.FieldSha256)
	return u
}

// SetTextPreview sets the "text_preview" field.
func (u *WebChatAttachmentUpsert) SetTextPreview(v string) *WebChatAttachmentUpsert {
	u.Set(webchatattachment.FieldTextPreview, v)
	return u
}

// UpdateTextPreview sets the "text_preview" field to the value that was provided on create.
func (u *WebChatAttachmentUpsert) UpdateTextPreview() *WebChatAttachmentUpsert {
	u.SetExcluded(webchatattachment.FieldTextPreview)
	return u
}

// ClearTextPreview clears the value of the "text_preview" field.
func (u *WebChatAttachmentUpsert) ClearTextPreview() *WebChatAttachmentUpsert {
	u.SetNull(webchatattachment.FieldTextPreview)
	return u
}

// SetStatus sets the "status" field.
func (u *WebChatAttachmentUpsert) SetStatus(v string) *WebChatAttachmentUpsert {
	u.Set(webchatattachment.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WebChatAttachmentUpsert) UpdateStatus() *WebChatAttachmentUpsert {
	u.SetExcluded(webchatattachment.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WebChatAttachment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WebChatAttachmentUpsertOne) UpdateNewValues() *WebChatAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(webchatattachment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WebChatAttachment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WebChatAttachmentUpsertOne) Ignore() *WebChatAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebChatAttachmentUpsertOne) DoNothing() *WebChatAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebChatAttachmentCreate.OnConflict
// documentation for more info.
func (u *WebChatAttachmentUpsertOne) Update(set func(*WebChatAttachmentUpsert)) *WebChatAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebChatAttachmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetMessageID sets the "message_id" field.
func (u *WebChatAttachmentUpsertOne) SetMessageID(v int64) *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetMessageID(v)
	})
}

// AddMessageID adds v to the "message_id" field.
func (u *WebChatAttachmentUpsertOne) AddMessageID(v int64) *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.AddMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertOne) UpdateMessageID() *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateMessageID()
	})
}

// ClearMessageID clears the value of the "message_id" field.
func (u *WebChatAttachmentUpsertOne) ClearMessageID() *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.ClearMessageID()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *WebChatAttachmentUpsertOne) SetConversationID(v int64) *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetConversationID(v)
	})
}

// AddConversationID adds v to the "conversation_id" field.
func (u *WebChatAttachmentUpsertOne) AddConversationID(v int64) *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.AddConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertOne) UpdateConversationID() *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateConversationID()
	})
}

// ClearConversationID clears the value of the "conversation_id" field.
func (u *WebChatAttachmentUpsertOne) ClearConversationID() *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.ClearConversationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *WebChatAttachmentUpsertOne) SetUserID(v int64) *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *WebChatAttachmentUpsertOne) AddUserID(v int64) *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertOne) UpdateUserID() *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateUserID()
	})
}

// SetKind sets the "kind" field.
func (u *WebChatAttachmentUpsertOne) SetKind(v string) *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertOne) UpdateKind() *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateKind()
	})
}

// SetFilename sets the "filename" field.
func (u *WebChatAttachmentUpsertOne) SetFilename(v string) *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetFilename(v)
	})
}

// UpdateFilename sets the "filename" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertOne) UpdateFilename() *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateFilename()
	})
}

// SetContentType sets the "content_type" field.
func (u *WebChatAttachmentUpsertOne) SetContentType(v string) *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertOne) UpdateContentType() *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateContentType()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *WebChatAttachmentUpsertOne) SetSizeBytes(v int64) *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *WebChatAttachmentUpsertOne) AddSizeBytes(v int64) *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertOne) UpdateSizeBytes() *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *WebChatAttachmentUpsertOne) SetStorageKey(v string) *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertOne) UpdateStorageKey() *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateStorageKey()
	})
}

// SetSha256 sets the "sha256" field.
func (u *WebChatAttachmentUpsertOne) SetSha256(v string) *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertOne) UpdateSha256() *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateSha256()
	})
}

// SetTextPreview sets the "text_preview" field.
func (u *WebChatAttachmentUpsertOne) SetTextPreview(v string) *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetTextPreview(v)
	})
}

// UpdateTextPreview sets the "text_preview" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertOne) UpdateTextPreview() *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateTextPreview()
	})
}

// ClearTextPreview clears the value of the "text_preview" field.
func (u *WebChatAttachmentUpsertOne) ClearTextPreview() *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.ClearTextPreview()
	})
}

// SetStatus sets the "status" field.
func (u *WebChatAttachmentUpsertOne) SetStatus(v string) *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertOne) UpdateStatus() *WebChatAttachmentUpsertOne {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *WebChatAttachmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebChatAttachmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebChatAttachmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WebChatAttachmentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WebChatAttachmentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WebChatAttachmentCreateBulk is the builder for creating many WebChatAttachment entities in bulk.
type WebChatAttachmentCreateBulk struct {
	config
	err      error
	builders []*WebChatAttachmentCreate
	conflict []sql.ConflictOption
}

// Save creates the WebChatAttachment entities in the database.
func (_c *WebChatAttachmentCreateBulk) Save(ctx context.Context) ([]*WebChatAttachment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WebChatAttachment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebChatAttachmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WebChatAttachmentCreateBulk) SaveX(ctx context.Context) []*WebChatAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebChatAttachmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebChatAttachmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WebChatAttachment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebChatAttachmentUpsert) {
//			SetMessageID(v+v).
//		}).
//		Exec(ctx)
func (_c *WebChatAttachmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *WebChatAttachmentUpsertBulk {
	_c.conflict = opts
	return &WebChatAttachmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WebChatAttachment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WebChatAttachmentCreateBulk) OnConflictColumns(columns ...string) *WebChatAttachmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WebChatAttachmentUpsertBulk{
		create: _c,
	}
}

// WebChatAttachmentUpsertBulk is the builder for "upsert"-ing
// a bulk of WebChatAttachment nodes.
type WebChatAttachmentUpsertBulk struct {
	create *WebChatAttachmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WebChatAttachment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WebChatAttachmentUpsertBulk) UpdateNewValues() *WebChatAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(webchatattachment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WebChatAttachment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WebChatAttachmentUpsertBulk) Ignore() *WebChatAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebChatAttachmentUpsertBulk) DoNothing() *WebChatAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebChatAttachmentCreateBulk.OnConflict
// documentation for more info.
func (u *WebChatAttachmentUpsertBulk) Update(set func(*WebChatAttachmentUpsert)) *WebChatAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebChatAttachmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetMessageID sets the "message_id" field.
func (u *WebChatAttachmentUpsertBulk) SetMessageID(v int64) *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetMessageID(v)
	})
}

// AddMessageID adds v to the "message_id" field.
func (u *WebChatAttachmentUpsertBulk) AddMessageID(v int64) *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.AddMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertBulk) UpdateMessageID() *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateMessageID()
	})
}

// ClearMessageID clears the value of the "message_id" field.
func (u *WebChatAttachmentUpsertBulk) ClearMessageID() *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.ClearMessageID()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *WebChatAttachmentUpsertBulk) SetConversationID(v int64) *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetConversationID(v)
	})
}

// AddConversationID adds v to the "conversation_id" field.
func (u *WebChatAttachmentUpsertBulk) AddConversationID(v int64) *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.AddConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertBulk) UpdateConversationID() *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateConversationID()
	})
}

// ClearConversationID clears the value of the "conversation_id" field.
func (u *WebChatAttachmentUpsertBulk) ClearConversationID() *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.ClearConversationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *WebChatAttachmentUpsertBulk) SetUserID(v int64) *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *WebChatAttachmentUpsertBulk) AddUserID(v int64) *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertBulk) UpdateUserID() *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateUserID()
	})
}

// SetKind sets the "kind" field.
func (u *WebChatAttachmentUpsertBulk) SetKind(v string) *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertBulk) UpdateKind() *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateKind()
	})
}

// SetFilename sets the "filename" field.
func (u *WebChatAttachmentUpsertBulk) SetFilename(v string) *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetFilename(v)
	})
}

// UpdateFilename sets the "filename" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertBulk) UpdateFilename() *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateFilename()
	})
}

// SetContentType sets the "content_type" field.
func (u *WebChatAttachmentUpsertBulk) SetContentType(v string) *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertBulk) UpdateContentType() *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateContentType()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *WebChatAttachmentUpsertBulk) SetSizeBytes(v int64) *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *WebChatAttachmentUpsertBulk) AddSizeBytes(v int64) *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertBulk) UpdateSizeBytes() *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *WebChatAttachmentUpsertBulk) SetStorageKey(v string) *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertBulk) UpdateStorageKey() *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateStorageKey()
	})
}

// SetSha256 sets the "sha256" field.
func (u *WebChatAttachmentUpsertBulk) SetSha256(v string) *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertBulk) UpdateSha256() *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateSha256()
	})
}

// SetTextPreview sets the "text_preview" field.
func (u *WebChatAttachmentUpsertBulk) SetTextPreview(v string) *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetTextPreview(v)
	})
}

// UpdateTextPreview sets the "text_preview" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertBulk) UpdateTextPreview() *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateTextPreview()
	})
}

// ClearTextPreview clears the value of the "text_preview" field.
func (u *WebChatAttachmentUpsertBulk) ClearTextPreview() *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.ClearTextPreview()
	})
}

// SetStatus sets the "status" field.
func (u *WebChatAttachmentUpsertBulk) SetStatus(v string) *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WebChatAttachmentUpsertBulk) UpdateStatus() *WebChatAttachmentUpsertBulk {
	return u.Update(func(s *WebChatAttachmentUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *WebChatAttachmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WebChatAttachmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebChatAttachmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebChatAttachmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
