// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/webchatartifact"
)

// WebChatArtifactUpdate is the builder for updating WebChatArtifact entities.
type WebChatArtifactUpdate struct {
	config
	hooks    []Hook
	mutation *WebChatArtifactMutation
}

// Where appends a list predicates to the WebChatArtifactUpdate builder.
func (_u *WebChatArtifactUpdate) Where(ps ...predicate.WebChatArtifact) *WebChatArtifactUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *WebChatArtifactUpdate) SetMessageID(v int64) *WebChatArtifactUpdate {
	_u.mutation.ResetMessageID()
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *WebChatArtifactUpdate) SetNillableMessageID(v *int64) *WebChatArtifactUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// AddMessageID adds value to the "message_id" field.
func (_u *WebChatArtifactUpdate) AddMessageID(v int64) *WebChatArtifactUpdate {
	_u.mutation.AddMessageID(v)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *WebChatArtifactUpdate) SetConversationID(v int64) *WebChatArtifactUpdate {
	_u.mutation.ResetConversationID()
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *WebChatArtifactUpdate) SetNillableConversationID(v *int64) *WebChatArtifactUpdate {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// AddConversationID adds value to the "conversation_id" field.
func (_u *WebChatArtifactUpdate) AddConversationID(v int64) *WebChatArtifactUpdate {
	_u.mutation.AddConversationID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *WebChatArtifactUpdate) SetUserID(v int64) *WebChatArtifactUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WebChatArtifactUpdate) SetNillableUserID(v *int64) *WebChatArtifactUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *WebChatArtifactUpdate) AddUserID(v int64) *WebChatArtifactUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetFilename sets the "filename" field.
func (_u *WebChatArtifactUpdate) SetFilename(v string) *WebChatArtifactUpdate {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *WebChatArtifactUpdate) SetNillableFilename(v *string) *WebChatArtifactUpdate {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *WebChatArtifactUpdate) SetContentType(v string) *WebChatArtifactUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *WebChatArtifactUpdate) SetNillableContentType(v *string) *WebChatArtifactUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *WebChatArtifactUpdate) SetSizeBytes(v int64) *WebChatArtifactUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *WebChatArtifactUpdate) SetNillableSizeBytes(v *int64) *WebChatArtifactUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *WebChatArtifactUpdate) AddSizeBytes(v int64) *WebChatArtifactUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetStorageKey sets the "storage_key" field.
func (_u *WebChatArtifactUpdate) SetStorageKey(v string) *WebChatArtifactUpdate {
	_u.mutation.SetStorageKey(v)
	return _u
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_u *WebChatArtifactUpdate) SetNillableStorageKey(v *string) *WebChatArtifactUpdate {
	if v != nil {
		_u.SetStorageKey(*v)
	}
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *WebChatArtifactUpdate) SetSha256(v string) *WebChatArtifactUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *WebChatArtifactUpdate) SetNillableSha256(v *string) *WebChatArtifactUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *WebChatArtifactUpdate) SetSource(v string) *WebChatArtifactUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *WebChatArtifactUpdate) SetNillableSource(v *string) *WebChatArtifactUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// Mutation returns the WebChatArtifactMutation object of the builder.
func (_u *WebChatArtifactUpdate) Mutation() *WebChatArtifactMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WebChatArtifactUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebChatArtifactUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WebChatArtifactUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebChatArtifactUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WebChatArtifactUpdate) check() error {
	if v, ok := _u.mutation.Filename(); ok {
		if err := webchatartifact.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "WebChatArtifact.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := webchatartifact.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "WebChatArtifact.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StorageKey(); ok {
		if err := webchatartifact.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "WebChatArtifact.storage_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := webchatartifact.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "WebChatArtifact.sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := webchatartifact.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "WebChatArtifact.source": %w`, err)}
		}
	}
	return nil
}

func (_u *WebChatArtifactUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(webchatartifact.Table, webchatartifact.Columns, sqlgraph.NewFieldSpec(webchatartifact.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(webchatartifact.FieldMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMessageID(); ok {
		_spec.AddField(webchatartifact.FieldMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ConversationID(); ok {
		_spec.SetField(webchatartifact.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConversationID(); ok {
		_spec.AddField(webchatartifact.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(webchatartifact.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(webchatartifact.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(webchatartifact.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(webchatartifact.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(webchatartifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(webchatartifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StorageKey(); ok {
		_spec.SetField(webchatartifact.FieldStorageKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(webchatartifact.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(webchatartifact.FieldSource, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webchatartifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WebChatArtifactUpdateOne is the builder for updating a single WebChatArtifact entity.
type WebChatArtifactUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WebChatArtifactMutation
}

// SetMessageID sets the "message_id" field.
func (_u *WebChatArtifactUpdateOne) SetMessageID(v int64) *WebChatArtifactUpdateOne {
	_u.mutation.ResetMessageID()
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *WebChatArtifactUpdateOne) SetNillableMessageID(v *int64) *WebChatArtifactUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// AddMessageID adds value to the "message_id" field.
func (_u *WebChatArtifactUpdateOne) AddMessageID(v int64) *WebChatArtifactUpdateOne {
	_u.mutation.AddMessageID(v)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *WebChatArtifactUpdateOne) SetConversationID(v int64) *WebChatArtifactUpdateOne {
	_u.mutation.ResetConversationID()
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *WebChatArtifactUpdateOne) SetNillableConversationID(v *int64) *WebChatArtifactUpdateOne {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// AddConversationID adds value to the "conversation_id" field.
func (_u *WebChatArtifactUpdateOne) AddConversationID(v int64) *WebChatArtifactUpdateOne {
	_u.mutation.AddConversationID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *WebChatArtifactUpdateOne) SetUserID(v int64) *WebChatArtifactUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WebChatArtifactUpdateOne) SetNillableUserID(v *int64) *WebChatArtifactUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *WebChatArtifactUpdateOne) AddUserID(v int64) *WebChatArtifactUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetFilename sets the "filename" field.
func (_u *WebChatArtifactUpdateOne) SetFilename(v string) *WebChatArtifactUpdateOne {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *WebChatArtifactUpdateOne) SetNillableFilename(v *string) *WebChatArtifactUpdateOne {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *WebChatArtifactUpdateOne) SetContentType(v string) *WebChatArtifactUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *WebChatArtifactUpdateOne) SetNillableContentType(v *string) *WebChatArtifactUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *WebChatArtifactUpdateOne) SetSizeBytes(v int64) *WebChatArtifactUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *WebChatArtifactUpdateOne) SetNillableSizeBytes(v *int64) *WebChatArtifactUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *WebChatArtifactUpdateOne) AddSizeBytes(v int64) *WebChatArtifactUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetStorageKey sets the "storage_key" field.
func (_u *WebChatArtifactUpdateOne) SetStorageKey(v string) *WebChatArtifactUpdateOne {
	_u.mutation.SetStorageKey(v)
	return _u
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_u *WebChatArtifactUpdateOne) SetNillableStorageKey(v *string) *WebChatArtifactUpdateOne {
	if v != nil {
		_u.SetStorageKey(*v)
	}
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *WebChatArtifactUpdateOne) SetSha256(v string) *WebChatArtifactUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *WebChatArtifactUpdateOne) SetNillableSha256(v *string) *WebChatArtifactUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *WebChatArtifactUpdateOne) SetSource(v string) *WebChatArtifactUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *WebChatArtifactUpdateOne) SetNillableSource(v *string) *WebChatArtifactUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// Mutation returns the WebChatArtifactMutation object of the builder.
func (_u *WebChatArtifactUpdateOne) Mutation() *WebChatArtifactMutation {
	return _u.mutation
}

// Where appends a list predicates to the WebChatArtifactUpdate builder.
func (_u *WebChatArtifactUpdateOne) Where(ps ...predicate.WebChatArtifact) *WebChatArtifactUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WebChatArtifactUpdateOne) Select(field string, fields ...string) *WebChatArtifactUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WebChatArtifact entity.
func (_u *WebChatArtifactUpdateOne) Save(ctx context.Context) (*WebChatArtifact, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebChatArtifactUpdateOne) SaveX(ctx context.Context) *WebChatArtifact {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WebChatArtifactUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebChatArtifactUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WebChatArtifactUpdateOne) check() error {
	if v, ok := _u.mutation.Filename(); ok {
		if err := webchatartifact.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "WebChatArtifact.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := webchatartifact.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "WebChatArtifact.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StorageKey(); ok {
		if err := webchatartifact.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "WebChatArtifact.storage_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := webchatartifact.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "WebChatArtifact.sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := webchatartifact.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "WebChatArtifact.source": %w`, err)}
		}
	}
	return nil
}

func (_u *WebChatArtifactUpdateOne) sqlSave(ctx context.Context) (_node *WebChatArtifact, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(webchatartifact.Table, webchatartifact.Columns, sqlgraph.NewFieldSpec(webchatartifact.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WebChatArtifact.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webchatartifact.FieldID)
		for _, f := range fields {
			if !webchatartifact.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != webchatartifact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(webchatartifact.FieldMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMessageID(); ok {
		_spec.AddField(webchatartifact.FieldMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ConversationID(); ok {
		_spec.SetField(webchatartifact.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConversationID(); ok {
		_spec.AddField(webchatartifact.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(webchatartifact.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(webchatartifact.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(webchatartifact.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(webchatartifact.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(webchatartifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(webchatartifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StorageKey(); ok {
		_spec.SetField(webchatartifact.FieldStorageKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(webchatartifact.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(webchatartifact.FieldSource, field.TypeString, value)
	}
	_node = &WebChatArtifact{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webchatartifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
