// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/webchatmessage"
)

// WebChatMessageCreate is the builder for creating a WebChatMessage entity.
type WebChatMessageCreate struct {
	config
	mutation *WebChatMessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *WebChatMessageCreate) SetCreatedAt(v time.Time) *WebChatMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WebChatMessageCreate) SetNillableCreatedAt(v *time.Time) *WebChatMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WebChatMessageCreate) SetUpdatedAt(v time.Time) *WebChatMessageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WebChatMessageCreate) SetNillableUpdatedAt(v *time.Time) *WebChatMessageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetConversationID sets the "conversation_id" field.
func (_c *WebChatMessageCreate) SetConversationID(v int64) *WebChatMessageCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *WebChatMessageCreate) SetUserID(v int64) *WebChatMessageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *WebChatMessageCreate) SetRole(v string) *WebChatMessageCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *WebChatMessageCreate) SetModel(v string) *WebChatMessageCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *WebChatMessageCreate) SetNillableModel(v *string) *WebChatMessageCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *WebChatMessageCreate) SetProvider(v string) *WebChatMessageCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *WebChatMessageCreate) SetNillableProvider(v *string) *WebChatMessageCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetContentText sets the "content_text" field.
func (_c *WebChatMessageCreate) SetContentText(v string) *WebChatMessageCreate {
	_c.mutation.SetContentText(v)
	return _c
}

// SetNillableContentText sets the "content_text" field if the given value is not nil.
func (_c *WebChatMessageCreate) SetNillableContentText(v *string) *WebChatMessageCreate {
	if v != nil {
		_c.SetContentText(*v)
	}
	return _c
}

// SetContentJSON sets the "content_json" field.
func (_c *WebChatMessageCreate) SetContentJSON(v []map[string]interface{}) *WebChatMessageCreate {
	_c.mutation.SetContentJSON(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *WebChatMessageCreate) SetStatus(v string) *WebChatMessageCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WebChatMessageCreate) SetNillableStatus(v *string) *WebChatMessageCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *WebChatMessageCreate) SetErrorCode(v string) *WebChatMessageCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *WebChatMessageCreate) SetNillableErrorCode(v *string) *WebChatMessageCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *WebChatMessageCreate) SetErrorMessage(v string) *WebChatMessageCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *WebChatMessageCreate) SetNillableErrorMessage(v *string) *WebChatMessageCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *WebChatMessageCreate) SetUsageLogID(v int64) *WebChatMessageCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_c *WebChatMessageCreate) SetNillableUsageLogID(v *int64) *WebChatMessageCreate {
	if v != nil {
		_c.SetUsageLogID(*v)
	}
	return _c
}

// Mutation returns the WebChatMessageMutation object of the builder.
func (_c *WebChatMessageCreate) Mutation() *WebChatMessageMutation {
	return _c.mutation
}

// Save creates the WebChatMessage in the database.
func (_c *WebChatMessageCreate) Save(ctx context.Context) (*WebChatMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WebChatMessageCreate) SaveX(ctx context.Context) *WebChatMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebChatMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebChatMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WebChatMessageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := webchatmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := webchatmessage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := webchatmessage.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := webchatmessage.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.ContentText(); !ok {
		v := webchatmessage.DefaultContentText
		_c.mutation.SetContentText(v)
	}
	if _, ok := _c.mutation.ContentJSON(); !ok {
		v := webchatmessage.DefaultContentJSON
		_c.mutation.SetContentJSON(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := webchatmessage.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WebChatMessageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WebChatMessage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WebChatMessage.updated_at"`)}
	}
	if _, ok := _c.mutation.ConversationID(); !ok {
		return &ValidationError{Name: "conversation_id", err: errors.New(`ent: missing required field "WebChatMessage.conversation_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "WebChatMessage.user_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "WebChatMessage.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := webchatmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "WebChatMessage.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "WebChatMessage.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := webchatmessage.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "WebChatMessage.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "WebChatMessage.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := webchatmessage.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "WebChatMessage.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentText(); !ok {
		return &ValidationError{Name: "content_text", err: errors.New(`ent: missing required field "WebChatMessage.content_text"`)}
	}
	if _, ok := _c.mutation.ContentJSON(); !ok {
		return &ValidationError{Name: "content_json", err: errors.New(`ent: missing required field "WebChatMessage.content_json"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WebChatMessage.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := webchatmessage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WebChatMessage.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := webchatmessage.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "WebChatMessage.error_code": %w`, err)}
		}
	}
	return nil
}

func (_c *WebChatMessageCreate) sqlSave(ctx context.Context) (*WebChatMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WebChatMessageCreate) createSpec() (*WebChatMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &WebChatMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(webchatmessage.Table, sqlgraph.NewFieldSpec(webchatmessage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(webchatmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(webchatmessage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ConversationID(); ok {
		_spec.SetField(webchatmessage.FieldConversationID, field.TypeInt64, value)
		_node.ConversationID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(webchatmessage.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(webchatmessage.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(webchatmessage.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(webchatmessage.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.ContentText(); ok {
		_spec.SetField(webchatmessage.FieldContentText, field.TypeString, value)
		_node.ContentText = value
	}
	if value, ok := _c.mutation.ContentJSON(); ok {
		_spec.SetField(webchatmessage.FieldContentJSON, field.TypeJSON, value)
		_node.ContentJSON = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(webchatmessage.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(webchatmessage.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(webchatmessage.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.UsageLogID(); ok {
		_spec.SetField(webchatmessage.FieldUsageLogID, field.TypeInt64, value)
		_node.UsageLogID = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WebChatMessage.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebChatMessageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WebChatMessageCreate) OnConflict(opts ...sql.ConflictOption) *WebChatMessageUpsertOne {
	_c.conflict = opts
	return &WebChatMessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WebChatMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WebChatMessageCreate) OnConflictColumns(columns ...string) *WebChatMessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WebChatMessageUpsertOne{
		create: _c,
	}
}

type (
	// WebChatMessageUpsertOne is the builder for "upsert"-ing
	//  one WebChatMessage node.
	WebChatMessageUpsertOne struct {
		create *WebChatMessageCreate
	}

	// WebChatMessageUpsert is the "OnConflict" setter.
	WebChatMessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *WebChatMessageUpsert) SetUpdatedAt(v time.Time) *WebChatMessageUpsert {
	u.Set(webchatmessage.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WebChatMessageUpsert) UpdateUpdatedAt() *WebChatMessageUpsert {
	u.SetExcluded(webchatmessage.FieldUpdatedAt)
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *WebChatMessageUpsert) SetConversationID(v int64) *WebChatMessageUpsert {
	u.Set(webchatmessage.FieldConversationID, v)
	return u
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *WebChatMessageUpsert) UpdateConversationID() *WebChatMessageUpsert {
	u.SetExcluded(webchatmessage.FieldConversationID)
	return u
}

// AddConversationID adds v to the "conversation_id" field.
func (u *WebChatMessageUpsert) AddConversationID(v int64) *WebChatMessageUpsert {
	u.Add(webchatmessage.FieldConversationID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *WebChatMessageUpsert) SetUserID(v int64) *WebChatMessageUpsert {
	u.Set(webchatmessage.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WebChatMessageUpsert) UpdateUserID() *WebChatMessageUpsert {
	u.SetExcluded(webchatmessage.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *WebChatMessageUpsert) AddUserID(v int64) *WebChatMessageUpsert {
	u.Add(webchatmessage.FieldUserID, v)
	return u
}

// SetRole sets the "role" field.
func (u *WebChatMessageUpsert) SetRole(v string) *WebChatMessageUpsert {
	u.Set(webchatmessage.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *WebChatMessageUpsert) UpdateRole() *WebChatMessageUpsert {
	u.SetExcluded(webchatmessage.FieldRole)
	return u
}

// SetModel sets the "model" field.
func (u *WebChatMessageUpsert) SetModel(v string) *WebChatMessageUpsert {
	u.Set(webchatmessage.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *WebChatMessageUpsert) UpdateModel() *WebChatMessageUpsert {
	u.SetExcluded(webchatmessage.FieldModel)
	return u
}

// SetProvider sets the "provider" field.
func (u *WebChatMessageUpsert) SetProvider(v string) *WebChatMessageUpsert {
	u.Set(webchatmessage.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *WebChatMessageUpsert) UpdateProvider() *WebChatMessageUpsert {
	u.SetExcluded(webchatmessage.FieldProvider)
	return u
}

// SetContentText sets the "content_text" field.
func (u *WebChatMessageUpsert) SetContentText(v string) *WebChatMessageUpsert {
	u.Set(webchatmessage.FieldContentText, v)
	return u
}

// UpdateContentText sets the "content_text" field to the value that was provided on create.
func (u *WebChatMessageUpsert) UpdateContentText() *WebChatMessageUpsert {
	u.SetExcluded(webchatmessage.FieldContentText)
	return u
}

// SetContentJSON sets the "content_json" field.
func (u *WebChatMessageUpsert) SetContentJSON(v []map[string]interface{}) *WebChatMessageUpsert {
	u.Set(webchatmessage.FieldContentJSON, v)
	return u
}

// UpdateContentJSON sets the "content_json" field to the value that was provided on create.
func (u *WebChatMessageUpsert) UpdateContentJSON() *WebChatMessageUpsert {
	u.SetExcluded(webchatmessage.FieldContentJSON)
	return u
}

// SetStatus sets the "status" field.
func (u *WebChatMessageUpsert) SetStatus(v string) *WebChatMessageUpsert {
	u.Set(webchatmessage.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WebChatMessageUpsert) UpdateStatus() *WebChatMessageUpsert {
	u.SetExcluded(webchatmessage.FieldStatus)
	return u
}

// SetErrorCode sets the "error_code" field.
func (u *WebChatMessageUpsert) SetErrorCode(v string) *WebChatMessageUpsert {
	u.Set(webchatmessage.FieldErrorCode, v)
	return u
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *WebChatMessageUpsert) UpdateErrorCode() *WebChatMessageUpsert {
	u.SetExcluded(webchatmessage.FieldErrorCode)
	return u
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *WebChatMessageUpsert) ClearErrorCode() *WebChatMessageUpsert {
	u.SetNull(webchatmessage.FieldErrorCode)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *WebChatMessageUpsert) SetErrorMessage(v string) *WebChatMessageUpsert {
	u.Set(webchatmessage.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *WebChatMessageUpsert) UpdateErrorMessage() *WebChatMessageUpsert {
	u.SetExcluded(webchatmessage.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *WebChatMessageUpsert) ClearErrorMessage() *WebChatMessageUpsert {
	u.SetNull(webchatmessage.FieldErrorMessage)
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *WebChatMessageUpsert) SetUsageLogID(v int64) *WebChatMessageUpsert {
	u.Set(webchatmessage.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *WebChatMessageUpsert) UpdateUsageLogID() *WebChatMessageUpsert {
	u.SetExcluded(webchatmessage.FieldUsageLogID)
	return u
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *WebChatMessageUpsert) AddUsageLogID(v int64) *WebChatMessageUpsert {
	u.Add(webchatmessage.FieldUsageLogID, v)
	return u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *WebChatMessageUpsert) ClearUsageLogID() *WebChatMessageUpsert {
	u.SetNull(webchatmessage.FieldUsageLogID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WebChatMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WebChatMessageUpsertOne) UpdateNewValues() *WebChatMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(webchatmessage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WebChatMessage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WebChatMessageUpsertOne) Ignore() *WebChatMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebChatMessageUpsertOne) DoNothing() *WebChatMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebChatMessageCreate.OnConflict
// documentation for more info.
func (u *WebChatMessageUpsertOne) Update(set func(*WebChatMessageUpsert)) *WebChatMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebChatMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WebChatMessageUpsertOne) SetUpdatedAt(v time.Time) *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WebChatMessageUpsertOne) UpdateUpdatedAt() *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *WebChatMessageUpsertOne) SetConversationID(v int64) *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetConversationID(v)
	})
}

// AddConversationID adds v to the "conversation_id" field.
func (u *WebChatMessageUpsertOne) AddConversationID(v int64) *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.AddConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *WebChatMessageUpsertOne) UpdateConversationID() *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateConversationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *WebChatMessageUpsertOne) SetUserID(v int64) *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *WebChatMessageUpsertOne) AddUserID(v int64) *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WebChatMessageUpsertOne) UpdateUserID() *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateUserID()
	})
}

// SetRole sets the "role" field.
func (u *WebChatMessageUpsertOne) SetRole(v string) *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *WebChatMessageUpsertOne) UpdateRole() *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateRole()
	})
}

// SetModel sets the "model" field.
func (u *WebChatMessageUpsertOne) SetModel(v string) *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *WebChatMessageUpsertOne) UpdateModel() *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateModel()
	})
}

// SetProvider sets the "provider" field.
func (u *WebChatMessageUpsertOne) SetProvider(v string) *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *WebChatMessageUpsertOne) UpdateProvider() *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateProvider()
	})
}

// SetContentText sets the "content_text" field.
func (u *WebChatMessageUpsertOne) SetContentText(v string) *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetContentText(v)
	})
}

// UpdateContentText sets the "content_text" field to the value that was provided on create.
func (u *WebChatMessageUpsertOne) UpdateContentText() *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateContentText()
	})
}

// SetContentJSON sets the "content_json" field.
func (u *WebChatMessageUpsertOne) SetContentJSON(v []map[string]interface{}) *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetContentJSON(v)
	})
}

// UpdateContentJSON sets the "content_json" field to the value that was provided on create.
func (u *WebChatMessageUpsertOne) UpdateContentJSON() *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateContentJSON()
	})
}

// SetStatus sets the "status" field.
func (u *WebChatMessageUpsertOne) SetStatus(v string) *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WebChatMessageUpsertOne) UpdateStatus() *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateStatus()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *WebChatMessageUpsertOne) SetErrorCode(v string) *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *WebChatMessageUpsertOne) UpdateErrorCode() *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *WebChatMessageUpsertOne) ClearErrorCode() *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.ClearErrorCode()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *WebChatMessageUpsertOne) SetErrorMessage(v string) *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *WebChatMessageUpsertOne) UpdateErrorMessage() *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *WebChatMessageUpsertOne) ClearErrorMessage() *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.ClearErrorMessage()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *WebChatMessageUpsertOne) SetUsageLogID(v int64) *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *WebChatMessageUpsertOne) AddUsageLogID(v int64) *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *WebChatMessageUpsertOne) UpdateUsageLogID() *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *WebChatMessageUpsertOne) ClearUsageLogID() *WebChatMessageUpsertOne {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.ClearUsageLogID()
	})
}

// Exec executes the query.
func (u *WebChatMessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebChatMessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebChatMessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WebChatMessageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WebChatMessageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WebChatMessageCreateBulk is the builder for creating many WebChatMessage entities in bulk.
type WebChatMessageCreateBulk struct {
	config
	err      error
	builders []*WebChatMessageCreate
	conflict []sql.ConflictOption
}

// Save creates the WebChatMessage entities in the database.
func (_c *WebChatMessageCreateBulk) Save(ctx context.Context) ([]*WebChatMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WebChatMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebChatMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WebChatMessageCreateBulk) SaveX(ctx context.Context) []*WebChatMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebChatMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebChatMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WebChatMessage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebChatMessageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WebChatMessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *WebChatMessageUpsertBulk {
	_c.conflict = opts
	return &WebChatMessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WebChatMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WebChatMessageCreateBulk) OnConflictColumns(columns ...string) *WebChatMessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WebChatMessageUpsertBulk{
		create: _c,
	}
}

// WebChatMessageUpsertBulk is the builder for "upsert"-ing
// a bulk of WebChatMessage nodes.
type WebChatMessageUpsertBulk struct {
	create *WebChatMessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WebChatMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WebChatMessageUpsertBulk) UpdateNewValues() *WebChatMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(webchatmessage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WebChatMessage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WebChatMessageUpsertBulk) Ignore() *WebChatMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebChatMessageUpsertBulk) DoNothing() *WebChatMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebChatMessageCreateBulk.OnConflict
// documentation for more info.
func (u *WebChatMessageUpsertBulk) Update(set func(*WebChatMessageUpsert)) *WebChatMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebChatMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WebChatMessageUpsertBulk) SetUpdatedAt(v time.Time) *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WebChatMessageUpsertBulk) UpdateUpdatedAt() *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *WebChatMessageUpsertBulk) SetConversationID(v int64) *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetConversationID(v)
	})
}

// AddConversationID adds v to the "conversation_id" field.
func (u *WebChatMessageUpsertBulk) AddConversationID(v int64) *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.AddConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *WebChatMessageUpsertBulk) UpdateConversationID() *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateConversationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *WebChatMessageUpsertBulk) SetUserID(v int64) *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *WebChatMessageUpsertBulk) AddUserID(v int64) *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WebChatMessageUpsertBulk) UpdateUserID() *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateUserID()
	})
}

// SetRole sets the "role" field.
func (u *WebChatMessageUpsertBulk) SetRole(v string) *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *WebChatMessageUpsertBulk) UpdateRole() *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateRole()
	})
}

// SetModel sets the "model" field.
func (u *WebChatMessageUpsertBulk) SetModel(v string) *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *WebChatMessageUpsertBulk) UpdateModel() *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateModel()
	})
}

// SetProvider sets the "provider" field.
func (u *WebChatMessageUpsertBulk) SetProvider(v string) *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *WebChatMessageUpsertBulk) UpdateProvider() *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateProvider()
	})
}

// SetContentText sets the "content_text" field.
func (u *WebChatMessageUpsertBulk) SetContentText(v string) *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetContentText(v)
	})
}

// UpdateContentText sets the "content_text" field to the value that was provided on create.
func (u *WebChatMessageUpsertBulk) UpdateContentText() *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateContentText()
	})
}

// SetContentJSON sets the "content_json" field.
func (u *WebChatMessageUpsertBulk) SetContentJSON(v []map[string]interface{}) *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetContentJSON(v)
	})
}

// UpdateContentJSON sets the "content_json" field to the value that was provided on create.
func (u *WebChatMessageUpsertBulk) UpdateContentJSON() *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateContentJSON()
	})
}

// SetStatus sets the "status" field.
func (u *WebChatMessageUpsertBulk) SetStatus(v string) *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WebChatMessageUpsertBulk) UpdateStatus() *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateStatus()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *WebChatMessageUpsertBulk) SetErrorCode(v string) *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *WebChatMessageUpsertBulk) UpdateErrorCode() *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *WebChatMessageUpsertBulk) ClearErrorCode() *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.ClearErrorCode()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *WebChatMessageUpsertBulk) SetErrorMessage(v string) *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *WebChatMessageUpsertBulk) UpdateErrorMessage() *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *WebChatMessageUpsertBulk) ClearErrorMessage() *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.ClearErrorMessage()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *WebChatMessageUpsertBulk) SetUsageLogID(v int64) *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *WebChatMessageUpsertBulk) AddUsageLogID(v int64) *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *WebChatMessageUpsertBulk) UpdateUsageLogID() *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *WebChatMessageUpsertBulk) ClearUsageLogID() *WebChatMessageUpsertBulk {
	return u.Update(func(s *WebChatMessageUpsert) {
		s.ClearUsageLogID()
	})
}

// Exec executes the query.
func (u *WebChatMessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WebChatMessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebChatMessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebChatMessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
