// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/webchatartifact"
)

// WebChatArtifactCreate is the builder for creating a WebChatArtifact entity.
type WebChatArtifactCreate struct {
	config
	mutation *WebChatArtifactMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMessageID sets the "message_id" field.
func (_c *WebChatArtifactCreate) SetMessageID(v int64) *WebChatArtifactCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetConversationID sets the "conversation_id" field.
func (_c *WebChatArtifactCreate) SetConversationID(v int64) *WebChatArtifactCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *WebChatArtifactCreate) SetUserID(v int64) *WebChatArtifactCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetFilename sets the "filename" field.
func (_c *WebChatArtifactCreate) SetFilename(v string) *WebChatArtifactCreate {
	_c.mutation.SetFilename(v)
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *WebChatArtifactCreate) SetContentType(v string) *WebChatArtifactCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *WebChatArtifactCreate) SetSizeBytes(v int64) *WebChatArtifactCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetStorageKey sets the "storage_key" field.
func (_c *WebChatArtifactCreate) SetStorageKey(v string) *WebChatArtifactCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *WebChatArtifactCreate) SetSha256(v string) *WebChatArtifactCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *WebChatArtifactCreate) SetSource(v string) *WebChatArtifactCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WebChatArtifactCreate) SetCreatedAt(v time.Time) *WebChatArtifactCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WebChatArtifactCreate) SetNillableCreatedAt(v *time.Time) *WebChatArtifactCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the WebChatArtifactMutation object of the builder.
func (_c *WebChatArtifactCreate) Mutation() *WebChatArtifactMutation {
	return _c.mutation
}

// Save creates the WebChatArtifact in the database.
func (_c *WebChatArtifactCreate) Save(ctx context.Context) (*WebChatArtifact, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WebChatArtifactCreate) SaveX(ctx context.Context) *WebChatArtifact {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebChatArtifactCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebChatArtifactCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WebChatArtifactCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := webchatartifact.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WebChatArtifactCreate) check() error {
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "WebChatArtifact.message_id"`)}
	}
	if _, ok := _c.mutation.ConversationID(); !ok {
		return &ValidationError{Name: "conversation_id", err: errors.New(`ent: missing required field "WebChatArtifact.conversation_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "WebChatArtifact.user_id"`)}
	}
	if _, ok := _c.mutation.Filename(); !ok {
		return &ValidationError{Name: "filename", err: errors.New(`ent: missing required field "WebChatArtifact.filename"`)}
	}
	if v, ok := _c.mutation.Filename(); ok {
		if err := webchatartifact.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "WebChatArtifact.filename": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "WebChatArtifact.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := webchatartifact.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "WebChatArtifact.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "WebChatArtifact.size_bytes"`)}
	}
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "WebChatArtifact.storage_key"`)}
	}
	if v, ok := _c.mutation.StorageKey(); ok {
		if err := webchatartifact.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "WebChatArtifact.storage_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`ent: missing required field "WebChatArtifact.sha256"`)}
	}
	if v, ok := _c.mutation.Sha256(); ok {
		if err := webchatartifact.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "WebChatArtifact.sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "WebChatArtifact.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := webchatartifact.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "WebChatArtifact.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WebChatArtifact.created_at"`)}
	}
	return nil
}

func (_c *WebChatArtifactCreate) sqlSave(ctx context.Context) (*WebChatArtifact, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WebChatArtifactCreate) createSpec() (*WebChatArtifact, *sqlgraph.CreateSpec) {
	var (
		_node = &WebChatArtifact{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(webchatartifact.Table, sqlgraph.NewFieldSpec(webchatartifact.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(webchatartifact.FieldMessageID, field.TypeInt64, value)
		_node.MessageID = value
	}
	if value, ok := _c.mutation.ConversationID(); ok {
		_spec.SetField(webchatartifact.FieldConversationID, field.TypeInt64, value)
		_node.ConversationID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(webchatartifact.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Filename(); ok {
		_spec.SetField(webchatartifact.FieldFilename, field.TypeString, value)
		_node.Filename = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(webchatartifact.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(webchatartifact.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(webchatartifact.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(webchatartifact.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(webchatartifact.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(webchatartifact.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WebChatArtifact.Create().
//		SetMessageID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebChatArtifactUpsert) {
//			SetMessageID(v+v).
//		}).
//		Exec(ctx)
func (_c *WebChatArtifactCreate) OnConflict(opts ...sql.ConflictOption) *WebChatArtifactUpsertOne {
	_c.conflict = opts
	return &WebChatArtifactUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WebChatArtifact.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WebChatArtifactCreate) OnConflictColumns(columns ...string) *WebChatArtifactUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WebChatArtifactUpsertOne{
		create: _c,
	}
}

type (
	// WebChatArtifactUpsertOne is the builder for "upsert"-ing
	//  one WebChatArtifact node.
	WebChatArtifactUpsertOne struct {
		create *WebChatArtifactCreate
	}

	// WebChatArtifactUpsert is the "OnConflict" setter.
	WebChatArtifactUpsert struct {
		*sql.UpdateSet
	}
)

// SetMessageID sets the "message_id" field.
func (u *WebChatArtifactUpsert) SetMessageID(v int64) *WebChatArtifactUpsert {
	u.Set(webchatartifact.FieldMessageID, v)
	return u
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *WebChatArtifactUpsert) UpdateMessageID() *WebChatArtifactUpsert {
	u.SetExcluded(webchatartifact.FieldMessageID)
	return u
}

// AddMessageID adds v to the "message_id" field.
func (u *WebChatArtifactUpsert) AddMessageID(v int64) *WebChatArtifactUpsert {
	u.Add(webchatartifact.FieldMessageID, v)
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *WebChatArtifactUpsert) SetConversationID(v int64) *WebChatArtifactUpsert {
	u.Set(webchatartifact.FieldConversationID, v)
	return u
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *WebChatArtifactUpsert) UpdateConversationID() *WebChatArtifactUpsert {
	u.SetExcluded(webchatartifact.FieldConversationID)
	return u
}

// AddConversationID adds v to the "conversation_id" field.
func (u *WebChatArtifactUpsert) AddConversationID(v int64) *WebChatArtifactUpsert {
	u.Add(webchatartifact.FieldConversationID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *WebChatArtifactUpsert) SetUserID(v int64) *WebChatArtifactUpsert {
	u.Set(webchatartifact.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WebChatArtifactUpsert) UpdateUserID() *WebChatArtifactUpsert {
	u.SetExcluded(webchatartifact.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *WebChatArtifactUpsert) AddUserID(v int64) *WebChatArtifactUpsert {
	u.Add(webchatartifact.FieldUserID, v)
	return u
}

// SetFilename sets the "filename" field.
func (u *WebChatArtifactUpsert) SetFilename(v string) *WebChatArtifactUpsert {
	u.Set(webchatartifact.FieldFilename, v)
	return u
}

// UpdateFilename sets the "filename" field to the value that was provided on create.
func (u *WebChatArtifactUpsert) UpdateFilename() *WebChatArtifactUpsert {
	u.SetExcluded(webchatartifact.FieldFilename)
	return u
}

// SetContentType sets the "content_type" field.
func (u *WebChatArtifactUpsert) SetContentType(v string) *WebChatArtifactUpsert {
	u.Set(webchatartifact.FieldContentType, v)
	return u
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *WebChatArtifactUpsert) UpdateContentType() *WebChatArtifactUpsert {
	u.SetExcluded(webchatartifact.FieldContentType)
	return u
}

// SetSizeBytes sets the "size_bytes" field.
func (u *WebChatArtifactUpsert) SetSizeBytes(v int64) *WebChatArtifactUpsert {
	u.Set(webchatartifact.FieldSizeBytes, v)
	return u
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *WebChatArtifactUpsert) UpdateSizeBytes() *WebChatArtifactUpsert {
	u.SetExcluded(webchatartifact.FieldSizeBytes)
	return u
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *WebChatArtifactUpsert) AddSizeBytes(v int64) *WebChatArtifactUpsert {
	u.Add(webchatartifact.FieldSizeBytes, v)
	return u
}

// SetStorageKey sets the "storage_key" field.
func (u *WebChatArtifactUpsert) SetStorageKey(v string) *WebChatArtifactUpsert {
	u.Set(webchatartifact.FieldStorageKey, v)
	return u
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *WebChatArtifactUpsert) UpdateStorageKey() *WebChatArtifactUpsert {
	u.SetExcluded(webchatartifact.FieldStorageKey)
	return u
}

// SetSha256 sets the "sha256" field.
func (u *WebChatArtifactUpsert) SetSha256(v string) *WebChatArtifactUpsert {
	u.Set(webchatartifact.FieldSha256, v)
	return u
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *WebChatArtifactUpsert) UpdateSha256() *WebChatArtifactUpsert {
	u.SetExcluded(webchatartifact.FieldSha256)
	return u
}

// SetSource sets the "source" field.
func (u *WebChatArtifactUpsert) SetSource(v string) *WebChatArtifactUpsert {
	u.Set(webchatartifact.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *WebChatArtifactUpsert) UpdateSource() *WebChatArtifactUpsert {
	u.SetExcluded(webchatartifact.FieldSource)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WebChatArtifact.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WebChatArtifactUpsertOne) UpdateNewValues() *WebChatArtifactUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(webchatartifact.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WebChatArtifact.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WebChatArtifactUpsertOne) Ignore() *WebChatArtifactUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebChatArtifactUpsertOne) DoNothing() *WebChatArtifactUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebChatArtifactCreate.OnConflict
// documentation for more info.
func (u *WebChatArtifactUpsertOne) Update(set func(*WebChatArtifactUpsert)) *WebChatArtifactUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebChatArtifactUpsert{UpdateSet: update})
	}))
	return u
}

// SetMessageID sets the "message_id" field.
func (u *WebChatArtifactUpsertOne) SetMessageID(v int64) *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetMessageID(v)
	})
}

// AddMessageID adds v to the "message_id" field.
func (u *WebChatArtifactUpsertOne) AddMessageID(v int64) *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.AddMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *WebChatArtifactUpsertOne) UpdateMessageID() *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateMessageID()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *WebChatArtifactUpsertOne) SetConversationID(v int64) *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetConversationID(v)
	})
}

// AddConversationID adds v to the "conversation_id" field.
func (u *WebChatArtifactUpsertOne) AddConversationID(v int64) *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.AddConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *WebChatArtifactUpsertOne) UpdateConversationID() *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateConversationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *WebChatArtifactUpsertOne) SetUserID(v int64) *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *WebChatArtifactUpsertOne) AddUserID(v int64) *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WebChatArtifactUpsertOne) UpdateUserID() *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateUserID()
	})
}

// SetFilename sets the "filename" field.
func (u *WebChatArtifactUpsertOne) SetFilename(v string) *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetFilename(v)
	})
}

// UpdateFilename sets the "filename" field to the value that was provided on create.
func (u *WebChatArtifactUpsertOne) UpdateFilename() *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateFilename()
	})
}

// SetContentType sets the "content_type" field.
func (u *WebChatArtifactUpsertOne) SetContentType(v string) *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *WebChatArtifactUpsertOne) UpdateContentType() *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateContentType()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *WebChatArtifactUpsertOne) SetSizeBytes(v int64) *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *WebChatArtifactUpsertOne) AddSizeBytes(v int64) *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *WebChatArtifactUpsertOne) UpdateSizeBytes() *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *WebChatArtifactUpsertOne) SetStorageKey(v string) *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *WebChatArtifactUpsertOne) UpdateStorageKey() *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateStorageKey()
	})
}

// SetSha256 sets the "sha256" field.
func (u *WebChatArtifactUpsertOne) SetSha256(v string) *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *WebChatArtifactUpsertOne) UpdateSha256() *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateSha256()
	})
}

// SetSource sets the "source" field.
func (u *WebChatArtifactUpsertOne) SetSource(v string) *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *WebChatArtifactUpsertOne) UpdateSource() *WebChatArtifactUpsertOne {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateSource()
	})
}

// Exec executes the query.
func (u *WebChatArtifactUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebChatArtifactCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebChatArtifactUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WebChatArtifactUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WebChatArtifactUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WebChatArtifactCreateBulk is the builder for creating many WebChatArtifact entities in bulk.
type WebChatArtifactCreateBulk struct {
	config
	err      error
	builders []*WebChatArtifactCreate
	conflict []sql.ConflictOption
}

// Save creates the WebChatArtifact entities in the database.
func (_c *WebChatArtifactCreateBulk) Save(ctx context.Context) ([]*WebChatArtifact, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WebChatArtifact, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebChatArtifactMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WebChatArtifactCreateBulk) SaveX(ctx context.Context) []*WebChatArtifact {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebChatArtifactCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebChatArtifactCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WebChatArtifact.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebChatArtifactUpsert) {
//			SetMessageID(v+v).
//		}).
//		Exec(ctx)
func (_c *WebChatArtifactCreateBulk) OnConflict(opts ...sql.ConflictOption) *WebChatArtifactUpsertBulk {
	_c.conflict = opts
	return &WebChatArtifactUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WebChatArtifact.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WebChatArtifactCreateBulk) OnConflictColumns(columns ...string) *WebChatArtifactUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WebChatArtifactUpsertBulk{
		create: _c,
	}
}

// WebChatArtifactUpsertBulk is the builder for "upsert"-ing
// a bulk of WebChatArtifact nodes.
type WebChatArtifactUpsertBulk struct {
	create *WebChatArtifactCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WebChatArtifact.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WebChatArtifactUpsertBulk) UpdateNewValues() *WebChatArtifactUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(webchatartifact.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WebChatArtifact.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WebChatArtifactUpsertBulk) Ignore() *WebChatArtifactUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebChatArtifactUpsertBulk) DoNothing() *WebChatArtifactUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebChatArtifactCreateBulk.OnConflict
// documentation for more info.
func (u *WebChatArtifactUpsertBulk) Update(set func(*WebChatArtifactUpsert)) *WebChatArtifactUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebChatArtifactUpsert{UpdateSet: update})
	}))
	return u
}

// SetMessageID sets the "message_id" field.
func (u *WebChatArtifactUpsertBulk) SetMessageID(v int64) *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetMessageID(v)
	})
}

// AddMessageID adds v to the "message_id" field.
func (u *WebChatArtifactUpsertBulk) AddMessageID(v int64) *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.AddMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *WebChatArtifactUpsertBulk) UpdateMessageID() *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateMessageID()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *WebChatArtifactUpsertBulk) SetConversationID(v int64) *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetConversationID(v)
	})
}

// AddConversationID adds v to the "conversation_id" field.
func (u *WebChatArtifactUpsertBulk) AddConversationID(v int64) *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.AddConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *WebChatArtifactUpsertBulk) UpdateConversationID() *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateConversationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *WebChatArtifactUpsertBulk) SetUserID(v int64) *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *WebChatArtifactUpsertBulk) AddUserID(v int64) *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WebChatArtifactUpsertBulk) UpdateUserID() *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateUserID()
	})
}

// SetFilename sets the "filename" field.
func (u *WebChatArtifactUpsertBulk) SetFilename(v string) *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetFilename(v)
	})
}

// UpdateFilename sets the "filename" field to the value that was provided on create.
func (u *WebChatArtifactUpsertBulk) UpdateFilename() *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateFilename()
	})
}

// SetContentType sets the "content_type" field.
func (u *WebChatArtifactUpsertBulk) SetContentType(v string) *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *WebChatArtifactUpsertBulk) UpdateContentType() *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateContentType()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *WebChatArtifactUpsertBulk) SetSizeBytes(v int64) *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *WebChatArtifactUpsertBulk) AddSizeBytes(v int64) *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *WebChatArtifactUpsertBulk) UpdateSizeBytes() *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *WebChatArtifactUpsertBulk) SetStorageKey(v string) *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *WebChatArtifactUpsertBulk) UpdateStorageKey() *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateStorageKey()
	})
}

// SetSha256 sets the "sha256" field.
func (u *WebChatArtifactUpsertBulk) SetSha256(v string) *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *WebChatArtifactUpsertBulk) UpdateSha256() *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateSha256()
	})
}

// SetSource sets the "source" field.
func (u *WebChatArtifactUpsertBulk) SetSource(v string) *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *WebChatArtifactUpsertBulk) UpdateSource() *WebChatArtifactUpsertBulk {
	return u.Update(func(s *WebChatArtifactUpsert) {
		s.UpdateSource()
	})
}

// Exec executes the query.
func (u *WebChatArtifactUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WebChatArtifactCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebChatArtifactCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebChatArtifactUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
