// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/webchatconversation"
)

// WebChatConversationCreate is the builder for creating a WebChatConversation entity.
type WebChatConversationCreate struct {
	config
	mutation *WebChatConversationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *WebChatConversationCreate) SetCreatedAt(v time.Time) *WebChatConversationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WebChatConversationCreate) SetNillableCreatedAt(v *time.Time) *WebChatConversationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WebChatConversationCreate) SetUpdatedAt(v time.Time) *WebChatConversationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WebChatConversationCreate) SetNillableUpdatedAt(v *time.Time) *WebChatConversationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *WebChatConversationCreate) SetUserID(v int64) *WebChatConversationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *WebChatConversationCreate) SetTitle(v string) *WebChatConversationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *WebChatConversationCreate) SetNillableTitle(v *string) *WebChatConversationCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetDefaultModel sets the "default_model" field.
func (_c *WebChatConversationCreate) SetDefaultModel(v string) *WebChatConversationCreate {
	_c.mutation.SetDefaultModel(v)
	return _c
}

// SetNillableDefaultModel sets the "default_model" field if the given value is not nil.
func (_c *WebChatConversationCreate) SetNillableDefaultModel(v *string) *WebChatConversationCreate {
	if v != nil {
		_c.SetDefaultModel(*v)
	}
	return _c
}

// SetDefaultProvider sets the "default_provider" field.
func (_c *WebChatConversationCreate) SetDefaultProvider(v string) *WebChatConversationCreate {
	_c.mutation.SetDefaultProvider(v)
	return _c
}

// SetNillableDefaultProvider sets the "default_provider" field if the given value is not nil.
func (_c *WebChatConversationCreate) SetNillableDefaultProvider(v *string) *WebChatConversationCreate {
	if v != nil {
		_c.SetDefaultProvider(*v)
	}
	return _c
}

// SetLastModel sets the "last_model" field.
func (_c *WebChatConversationCreate) SetLastModel(v string) *WebChatConversationCreate {
	_c.mutation.SetLastModel(v)
	return _c
}

// SetNillableLastModel sets the "last_model" field if the given value is not nil.
func (_c *WebChatConversationCreate) SetNillableLastModel(v *string) *WebChatConversationCreate {
	if v != nil {
		_c.SetLastModel(*v)
	}
	return _c
}

// SetLastProvider sets the "last_provider" field.
func (_c *WebChatConversationCreate) SetLastProvider(v string) *WebChatConversationCreate {
	_c.mutation.SetLastProvider(v)
	return _c
}

// SetNillableLastProvider sets the "last_provider" field if the given value is not nil.
func (_c *WebChatConversationCreate) SetNillableLastProvider(v *string) *WebChatConversationCreate {
	if v != nil {
		_c.SetLastProvider(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *WebChatConversationCreate) SetStatus(v string) *WebChatConversationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WebChatConversationCreate) SetNillableStatus(v *string) *WebChatConversationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMessageCount sets the "message_count" field.
func (_c *WebChatConversationCreate) SetMessageCount(v int) *WebChatConversationCreate {
	_c.mutation.SetMessageCount(v)
	return _c
}

// SetNillableMessageCount sets the "message_count" field if the given value is not nil.
func (_c *WebChatConversationCreate) SetNillableMessageCount(v *int) *WebChatConversationCreate {
	if v != nil {
		_c.SetMessageCount(*v)
	}
	return _c
}

// SetLastMessageAt sets the "last_message_at" field.
func (_c *WebChatConversationCreate) SetLastMessageAt(v time.Time) *WebChatConversationCreate {
	_c.mutation.SetLastMessageAt(v)
	return _c
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_c *WebChatConversationCreate) SetNillableLastMessageAt(v *time.Time) *WebChatConversationCreate {
	if v != nil {
		_c.SetLastMessageAt(*v)
	}
	return _c
}

// Mutation returns the WebChatConversationMutation object of the builder.
func (_c *WebChatConversationCreate) Mutation() *WebChatConversationMutation {
	return _c.mutation
}

// Save creates the WebChatConversation in the database.
func (_c *WebChatConversationCreate) Save(ctx context.Context) (*WebChatConversation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WebChatConversationCreate) SaveX(ctx context.Context) *WebChatConversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebChatConversationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebChatConversationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WebChatConversationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := webchatconversation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := webchatconversation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := webchatconversation.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.DefaultModel(); !ok {
		v := webchatconversation.DefaultDefaultModel
		_c.mutation.SetDefaultModel(v)
	}
	if _, ok := _c.mutation.DefaultProvider(); !ok {
		v := webchatconversation.DefaultDefaultProvider
		_c.mutation.SetDefaultProvider(v)
	}
	if _, ok := _c.mutation.LastModel(); !ok {
		v := webchatconversation.DefaultLastModel
		_c.mutation.SetLastModel(v)
	}
	if _, ok := _c.mutation.LastProvider(); !ok {
		v := webchatconversation.DefaultLastProvider
		_c.mutation.SetLastProvider(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := webchatconversation.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.MessageCount(); !ok {
		v := webchatconversation.DefaultMessageCount
		_c.mutation.SetMessageCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WebChatConversationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WebChatConversation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WebChatConversation.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "WebChatConversation.user_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "WebChatConversation.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := webchatconversation.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "WebChatConversation.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultModel(); !ok {
		return &ValidationError{Name: "default_model", err: errors.New(`ent: missing required field "WebChatConversation.default_model"`)}
	}
	if v, ok := _c.mutation.DefaultModel(); ok {
		if err := webchatconversation.DefaultModelValidator(v); err != nil {
			return &ValidationError{Name: "default_model", err: fmt.Errorf(`ent: validator failed for field "WebChatConversation.default_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultProvider(); !ok {
		return &ValidationError{Name: "default_provider", err: errors.New(`ent: missing required field "WebChatConversation.default_provider"`)}
	}
	if v, ok := _c.mutation.DefaultProvider(); ok {
		if err := webchatconversation.DefaultProviderValidator(v); err != nil {
			return &ValidationError{Name: "default_provider", err: fmt.Errorf(`ent: validator failed for field "WebChatConversation.default_provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastModel(); !ok {
		return &ValidationError{Name: "last_model", err: errors.New(`ent: missing required field "WebChatConversation.last_model"`)}
	}
	if v, ok := _c.mutation.LastModel(); ok {
		if err := webchatconversation.LastModelValidator(v); err != nil {
			return &ValidationError{Name: "last_model", err: fmt.Errorf(`ent: validator failed for field "WebChatConversation.last_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastProvider(); !ok {
		return &ValidationError{Name: "last_provider", err: errors.New(`ent: missing required field "WebChatConversation.last_provider"`)}
	}
	if v, ok := _c.mutation.LastProvider(); ok {
		if err := webchatconversation.LastProviderValidator(v); err != nil {
			return &ValidationError{Name: "last_provider", err: fmt.Errorf(`ent: validator failed for field "WebChatConversation.last_provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WebChatConversation.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := webchatconversation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WebChatConversation.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MessageCount(); !ok {
		return &ValidationError{Name: "message_count", err: errors.New(`ent: missing required field "WebChatConversation.message_count"`)}
	}
	return nil
}

func (_c *WebChatConversationCreate) sqlSave(ctx context.Context) (*WebChatConversation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WebChatConversationCreate) createSpec() (*WebChatConversation, *sqlgraph.CreateSpec) {
	var (
		_node = &WebChatConversation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(webchatconversation.Table, sqlgraph.NewFieldSpec(webchatconversation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(webchatconversation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(webchatconversation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(webchatconversation.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(webchatconversation.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.DefaultModel(); ok {
		_spec.SetField(webchatconversation.FieldDefaultModel, field.TypeString, value)
		_node.DefaultModel = value
	}
	if value, ok := _c.mutation.DefaultProvider(); ok {
		_spec.SetField(webchatconversation.FieldDefaultProvider, field.TypeString, value)
		_node.DefaultProvider = value
	}
	if value, ok := _c.mutation.LastModel(); ok {
		_spec.SetField(webchatconversation.FieldLastModel, field.TypeString, value)
		_node.LastModel = value
	}
	if value, ok := _c.mutation.LastProvider(); ok {
		_spec.SetField(webchatconversation.FieldLastProvider, field.TypeString, value)
		_node.LastProvider = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(webchatconversation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.MessageCount(); ok {
		_spec.SetField(webchatconversation.FieldMessageCount, field.TypeInt, value)
		_node.MessageCount = value
	}
	if value, ok := _c.mutation.LastMessageAt(); ok {
		_spec.SetField(webchatconversation.FieldLastMessageAt, field.TypeTime, value)
		_node.LastMessageAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WebChatConversation.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebChatConversationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WebChatConversationCreate) OnConflict(opts ...sql.ConflictOption) *WebChatConversationUpsertOne {
	_c.conflict = opts
	return &WebChatConversationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WebChatConversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WebChatConversationCreate) OnConflictColumns(columns ...string) *WebChatConversationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WebChatConversationUpsertOne{
		create: _c,
	}
}

type (
	// WebChatConversationUpsertOne is the builder for "upsert"-ing
	//  one WebChatConversation node.
	WebChatConversationUpsertOne struct {
		create *WebChatConversationCreate
	}

	// WebChatConversationUpsert is the "OnConflict" setter.
	WebChatConversationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *WebChatConversationUpsert) SetUpdatedAt(v time.Time) *WebChatConversationUpsert {
	u.Set(webchatconversation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WebChatConversationUpsert) UpdateUpdatedAt() *WebChatConversationUpsert {
	u.SetExcluded(webchatconversation.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *WebChatConversationUpsert) SetUserID(v int64) *WebChatConversationUpsert {
	u.Set(webchatconversation.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WebChatConversationUpsert) UpdateUserID() *WebChatConversationUpsert {
	u.SetExcluded(webchatconversation.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *WebChatConversationUpsert) AddUserID(v int64) *WebChatConversationUpsert {
	u.Add(webchatconversation.FieldUserID, v)
	return u
}

// SetTitle sets the "title" field.
func (u *WebChatConversationUpsert) SetTitle(v string) *WebChatConversationUpsert {
	u.Set(webchatconversation.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *WebChatConversationUpsert) UpdateTitle() *WebChatConversationUpsert {
	u.SetExcluded(webchatconversation.FieldTitle)
	return u
}

// SetDefaultModel sets the "default_model" field.
func (u *WebChatConversationUpsert) SetDefaultModel(v string) *WebChatConversationUpsert {
	u.Set(webchatconversation.FieldDefaultModel, v)
	return u
}

// UpdateDefaultModel sets the "default_model" field to the value that was provided on create.
func (u *WebChatConversationUpsert) UpdateDefaultModel() *WebChatConversationUpsert {
	u.SetExcluded(webchatconversation.FieldDefaultModel)
	return u
}

// SetDefaultProvider sets the "default_provider" field.
func (u *WebChatConversationUpsert) SetDefaultProvider(v string) *WebChatConversationUpsert {
	u.Set(webchatconversation.FieldDefaultProvider, v)
	return u
}

// UpdateDefaultProvider sets the "default_provider" field to the value that was provided on create.
func (u *WebChatConversationUpsert) UpdateDefaultProvider() *WebChatConversationUpsert {
	u.SetExcluded(webchatconversation.FieldDefaultProvider)
	return u
}

// SetLastModel sets the "last_model" field.
func (u *WebChatConversationUpsert) SetLastModel(v string) *WebChatConversationUpsert {
	u.Set(webchatconversation.FieldLastModel, v)
	return u
}

// UpdateLastModel sets the "last_model" field to the value that was provided on create.
func (u *WebChatConversationUpsert) UpdateLastModel() *WebChatConversationUpsert {
	u.SetExcluded(webchatconversation.FieldLastModel)
	return u
}

// SetLastProvider sets the "last_provider" field.
func (u *WebChatConversationUpsert) SetLastProvider(v string) *WebChatConversationUpsert {
	u.Set(webchatconversation.FieldLastProvider, v)
	return u
}

// UpdateLastProvider sets the "last_provider" field to the value that was provided on create.
func (u *WebChatConversationUpsert) UpdateLastProvider() *WebChatConversationUpsert {
	u.SetExcluded(webchatconversation.FieldLastProvider)
	return u
}

// SetStatus sets the "status" field.
func (u *WebChatConversationUpsert) SetStatus(v string) *WebChatConversationUpsert {
	u.Set(webchatconversation.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WebChatConversationUpsert) UpdateStatus() *WebChatConversationUpsert {
	u.SetExcluded(webchatconversation.FieldStatus)
	return u
}

// SetMessageCount sets the "message_count" field.
func (u *WebChatConversationUpsert) SetMessageCount(v int) *WebChatConversationUpsert {
	u.Set(webchatconversation.FieldMessageCount, v)
	return u
}

// UpdateMessageCount sets the "message_count" field to the value that was provided on create.
func (u *WebChatConversationUpsert) UpdateMessageCount() *WebChatConversationUpsert {
	u.SetExcluded(webchatconversation.FieldMessageCount)
	return u
}

// AddMessageCount adds v to the "message_count" field.
func (u *WebChatConversationUpsert) AddMessageCount(v int) *WebChatConversationUpsert {
	u.Add(webchatconversation.FieldMessageCount, v)
	return u
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *WebChatConversationUpsert) SetLastMessageAt(v time.Time) *WebChatConversationUpsert {
	u.Set(webchatconversation.FieldLastMessageAt, v)
	return u
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *WebChatConversationUpsert) UpdateLastMessageAt() *WebChatConversationUpsert {
	u.SetExcluded(webchatconversation.FieldLastMessageAt)
	return u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *WebChatConversationUpsert) ClearLastMessageAt() *WebChatConversationUpsert {
	u.SetNull(webchatconversation.FieldLastMessageAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WebChatConversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WebChatConversationUpsertOne) UpdateNewValues() *WebChatConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(webchatconversation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WebChatConversation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WebChatConversationUpsertOne) Ignore() *WebChatConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebChatConversationUpsertOne) DoNothing() *WebChatConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebChatConversationCreate.OnConflict
// documentation for more info.
func (u *WebChatConversationUpsertOne) Update(set func(*WebChatConversationUpsert)) *WebChatConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebChatConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WebChatConversationUpsertOne) SetUpdatedAt(v time.Time) *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WebChatConversationUpsertOne) UpdateUpdatedAt() *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *WebChatConversationUpsertOne) SetUserID(v int64) *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *WebChatConversationUpsertOne) AddUserID(v int64) *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WebChatConversationUpsertOne) UpdateUserID() *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateUserID()
	})
}

// SetTitle sets the "title" field.
func (u *WebChatConversationUpsertOne) SetTitle(v string) *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *WebChatConversationUpsertOne) UpdateTitle() *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateTitle()
	})
}

// SetDefaultModel sets the "default_model" field.
func (u *WebChatConversationUpsertOne) SetDefaultModel(v string) *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetDefaultModel(v)
	})
}

// UpdateDefaultModel sets the "default_model" field to the value that was provided on create.
func (u *WebChatConversationUpsertOne) UpdateDefaultModel() *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateDefaultModel()
	})
}

// SetDefaultProvider sets the "default_provider" field.
func (u *WebChatConversationUpsertOne) SetDefaultProvider(v string) *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetDefaultProvider(v)
	})
}

// UpdateDefaultProvider sets the "default_provider" field to the value that was provided on create.
func (u *WebChatConversationUpsertOne) UpdateDefaultProvider() *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateDefaultProvider()
	})
}

// SetLastModel sets the "last_model" field.
func (u *WebChatConversationUpsertOne) SetLastModel(v string) *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetLastModel(v)
	})
}

// UpdateLastModel sets the "last_model" field to the value that was provided on create.
func (u *WebChatConversationUpsertOne) UpdateLastModel() *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateLastModel()
	})
}

// SetLastProvider sets the "last_provider" field.
func (u *WebChatConversationUpsertOne) SetLastProvider(v string) *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetLastProvider(v)
	})
}

// UpdateLastProvider sets the "last_provider" field to the value that was provided on create.
func (u *WebChatConversationUpsertOne) UpdateLastProvider() *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateLastProvider()
	})
}

// SetStatus sets the "status" field.
func (u *WebChatConversationUpsertOne) SetStatus(v string) *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WebChatConversationUpsertOne) UpdateStatus() *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateStatus()
	})
}

// SetMessageCount sets the "message_count" field.
func (u *WebChatConversationUpsertOne) SetMessageCount(v int) *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetMessageCount(v)
	})
}

// AddMessageCount adds v to the "message_count" field.
func (u *WebChatConversationUpsertOne) AddMessageCount(v int) *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.AddMessageCount(v)
	})
}

// UpdateMessageCount sets the "message_count" field to the value that was provided on create.
func (u *WebChatConversationUpsertOne) UpdateMessageCount() *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateMessageCount()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *WebChatConversationUpsertOne) SetLastMessageAt(v time.Time) *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *WebChatConversationUpsertOne) UpdateLastMessageAt() *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateLastMessageAt()
	})
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *WebChatConversationUpsertOne) ClearLastMessageAt() *WebChatConversationUpsertOne {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.ClearLastMessageAt()
	})
}

// Exec executes the query.
func (u *WebChatConversationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebChatConversationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebChatConversationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WebChatConversationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WebChatConversationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WebChatConversationCreateBulk is the builder for creating many WebChatConversation entities in bulk.
type WebChatConversationCreateBulk struct {
	config
	err      error
	builders []*WebChatConversationCreate
	conflict []sql.ConflictOption
}

// Save creates the WebChatConversation entities in the database.
func (_c *WebChatConversationCreateBulk) Save(ctx context.Context) ([]*WebChatConversation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WebChatConversation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebChatConversationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WebChatConversationCreateBulk) SaveX(ctx context.Context) []*WebChatConversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebChatConversationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebChatConversationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WebChatConversation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebChatConversationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WebChatConversationCreateBulk) OnConflict(opts ...sql.ConflictOption) *WebChatConversationUpsertBulk {
	_c.conflict = opts
	return &WebChatConversationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WebChatConversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WebChatConversationCreateBulk) OnConflictColumns(columns ...string) *WebChatConversationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WebChatConversationUpsertBulk{
		create: _c,
	}
}

// WebChatConversationUpsertBulk is the builder for "upsert"-ing
// a bulk of WebChatConversation nodes.
type WebChatConversationUpsertBulk struct {
	create *WebChatConversationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WebChatConversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WebChatConversationUpsertBulk) UpdateNewValues() *WebChatConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(webchatconversation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WebChatConversation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WebChatConversationUpsertBulk) Ignore() *WebChatConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebChatConversationUpsertBulk) DoNothing() *WebChatConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebChatConversationCreateBulk.OnConflict
// documentation for more info.
func (u *WebChatConversationUpsertBulk) Update(set func(*WebChatConversationUpsert)) *WebChatConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebChatConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WebChatConversationUpsertBulk) SetUpdatedAt(v time.Time) *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WebChatConversationUpsertBulk) UpdateUpdatedAt() *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *WebChatConversationUpsertBulk) SetUserID(v int64) *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *WebChatConversationUpsertBulk) AddUserID(v int64) *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WebChatConversationUpsertBulk) UpdateUserID() *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateUserID()
	})
}

// SetTitle sets the "title" field.
func (u *WebChatConversationUpsertBulk) SetTitle(v string) *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *WebChatConversationUpsertBulk) UpdateTitle() *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateTitle()
	})
}

// SetDefaultModel sets the "default_model" field.
func (u *WebChatConversationUpsertBulk) SetDefaultModel(v string) *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetDefaultModel(v)
	})
}

// UpdateDefaultModel sets the "default_model" field to the value that was provided on create.
func (u *WebChatConversationUpsertBulk) UpdateDefaultModel() *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateDefaultModel()
	})
}

// SetDefaultProvider sets the "default_provider" field.
func (u *WebChatConversationUpsertBulk) SetDefaultProvider(v string) *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetDefaultProvider(v)
	})
}

// UpdateDefaultProvider sets the "default_provider" field to the value that was provided on create.
func (u *WebChatConversationUpsertBulk) UpdateDefaultProvider() *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateDefaultProvider()
	})
}

// SetLastModel sets the "last_model" field.
func (u *WebChatConversationUpsertBulk) SetLastModel(v string) *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetLastModel(v)
	})
}

// UpdateLastModel sets the "last_model" field to the value that was provided on create.
func (u *WebChatConversationUpsertBulk) UpdateLastModel() *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateLastModel()
	})
}

// SetLastProvider sets the "last_provider" field.
func (u *WebChatConversationUpsertBulk) SetLastProvider(v string) *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetLastProvider(v)
	})
}

// UpdateLastProvider sets the "last_provider" field to the value that was provided on create.
func (u *WebChatConversationUpsertBulk) UpdateLastProvider() *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateLastProvider()
	})
}

// SetStatus sets the "status" field.
func (u *WebChatConversationUpsertBulk) SetStatus(v string) *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WebChatConversationUpsertBulk) UpdateStatus() *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateStatus()
	})
}

// SetMessageCount sets the "message_count" field.
func (u *WebChatConversationUpsertBulk) SetMessageCount(v int) *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetMessageCount(v)
	})
}

// AddMessageCount adds v to the "message_count" field.
func (u *WebChatConversationUpsertBulk) AddMessageCount(v int) *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.AddMessageCount(v)
	})
}

// UpdateMessageCount sets the "message_count" field to the value that was provided on create.
func (u *WebChatConversationUpsertBulk) UpdateMessageCount() *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateMessageCount()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *WebChatConversationUpsertBulk) SetLastMessageAt(v time.Time) *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *WebChatConversationUpsertBulk) UpdateLastMessageAt() *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.UpdateLastMessageAt()
	})
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *WebChatConversationUpsertBulk) ClearLastMessageAt() *WebChatConversationUpsertBulk {
	return u.Update(func(s *WebChatConversationUpsert) {
		s.ClearLastMessageAt()
	})
}

// Exec executes the query.
func (u *WebChatConversationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WebChatConversationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebChatConversationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebChatConversationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
