// Code generated by ent, DO NOT EDIT.

package dailycheckinclaim

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldEQ(FieldUserID, v))
}

// ActivityStartAt applies equality check predicate on the "activity_start_at" field. It's identical to ActivityStartAtEQ.
func ActivityStartAt(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldEQ(FieldActivityStartAt, v))
}

// CheckInDate applies equality check predicate on the "check_in_date" field. It's identical to CheckInDateEQ.
func CheckInDate(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldEQ(FieldCheckInDate, v))
}

// RewardAmount applies equality check predicate on the "reward_amount" field. It's identical to RewardAmountEQ.
func RewardAmount(v float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldEQ(FieldRewardAmount, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldEQ(FieldBalanceAfter, v))
}

// ClaimedAt applies equality check predicate on the "claimed_at" field. It's identical to ClaimedAtEQ.
func ClaimedAt(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldEQ(FieldClaimedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldNotIn(FieldUserID, vs...))
}

// ActivityStartAtEQ applies the EQ predicate on the "activity_start_at" field.
func ActivityStartAtEQ(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldEQ(FieldActivityStartAt, v))
}

// ActivityStartAtNEQ applies the NEQ predicate on the "activity_start_at" field.
func ActivityStartAtNEQ(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldNEQ(FieldActivityStartAt, v))
}

// ActivityStartAtIn applies the In predicate on the "activity_start_at" field.
func ActivityStartAtIn(vs ...time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldIn(FieldActivityStartAt, vs...))
}

// ActivityStartAtNotIn applies the NotIn predicate on the "activity_start_at" field.
func ActivityStartAtNotIn(vs ...time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldNotIn(FieldActivityStartAt, vs...))
}

// ActivityStartAtGT applies the GT predicate on the "activity_start_at" field.
func ActivityStartAtGT(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldGT(FieldActivityStartAt, v))
}

// ActivityStartAtGTE applies the GTE predicate on the "activity_start_at" field.
func ActivityStartAtGTE(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldGTE(FieldActivityStartAt, v))
}

// ActivityStartAtLT applies the LT predicate on the "activity_start_at" field.
func ActivityStartAtLT(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldLT(FieldActivityStartAt, v))
}

// ActivityStartAtLTE applies the LTE predicate on the "activity_start_at" field.
func ActivityStartAtLTE(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldLTE(FieldActivityStartAt, v))
}

// CheckInDateEQ applies the EQ predicate on the "check_in_date" field.
func CheckInDateEQ(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldEQ(FieldCheckInDate, v))
}

// CheckInDateNEQ applies the NEQ predicate on the "check_in_date" field.
func CheckInDateNEQ(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldNEQ(FieldCheckInDate, v))
}

// CheckInDateIn applies the In predicate on the "check_in_date" field.
func CheckInDateIn(vs ...time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldIn(FieldCheckInDate, vs...))
}

// CheckInDateNotIn applies the NotIn predicate on the "check_in_date" field.
func CheckInDateNotIn(vs ...time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldNotIn(FieldCheckInDate, vs...))
}

// CheckInDateGT applies the GT predicate on the "check_in_date" field.
func CheckInDateGT(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldGT(FieldCheckInDate, v))
}

// CheckInDateGTE applies the GTE predicate on the "check_in_date" field.
func CheckInDateGTE(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldGTE(FieldCheckInDate, v))
}

// CheckInDateLT applies the LT predicate on the "check_in_date" field.
func CheckInDateLT(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldLT(FieldCheckInDate, v))
}

// CheckInDateLTE applies the LTE predicate on the "check_in_date" field.
func CheckInDateLTE(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldLTE(FieldCheckInDate, v))
}

// RewardAmountEQ applies the EQ predicate on the "reward_amount" field.
func RewardAmountEQ(v float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldEQ(FieldRewardAmount, v))
}

// RewardAmountNEQ applies the NEQ predicate on the "reward_amount" field.
func RewardAmountNEQ(v float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldNEQ(FieldRewardAmount, v))
}

// RewardAmountIn applies the In predicate on the "reward_amount" field.
func RewardAmountIn(vs ...float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldIn(FieldRewardAmount, vs...))
}

// RewardAmountNotIn applies the NotIn predicate on the "reward_amount" field.
func RewardAmountNotIn(vs ...float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldNotIn(FieldRewardAmount, vs...))
}

// RewardAmountGT applies the GT predicate on the "reward_amount" field.
func RewardAmountGT(v float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldGT(FieldRewardAmount, v))
}

// RewardAmountGTE applies the GTE predicate on the "reward_amount" field.
func RewardAmountGTE(v float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldGTE(FieldRewardAmount, v))
}

// RewardAmountLT applies the LT predicate on the "reward_amount" field.
func RewardAmountLT(v float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldLT(FieldRewardAmount, v))
}

// RewardAmountLTE applies the LTE predicate on the "reward_amount" field.
func RewardAmountLTE(v float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldLTE(FieldRewardAmount, v))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v float64) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldLTE(FieldBalanceAfter, v))
}

// ClaimedAtEQ applies the EQ predicate on the "claimed_at" field.
func ClaimedAtEQ(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldEQ(FieldClaimedAt, v))
}

// ClaimedAtNEQ applies the NEQ predicate on the "claimed_at" field.
func ClaimedAtNEQ(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldNEQ(FieldClaimedAt, v))
}

// ClaimedAtIn applies the In predicate on the "claimed_at" field.
func ClaimedAtIn(vs ...time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldIn(FieldClaimedAt, vs...))
}

// ClaimedAtNotIn applies the NotIn predicate on the "claimed_at" field.
func ClaimedAtNotIn(vs ...time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldNotIn(FieldClaimedAt, vs...))
}

// ClaimedAtGT applies the GT predicate on the "claimed_at" field.
func ClaimedAtGT(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldGT(FieldClaimedAt, v))
}

// ClaimedAtGTE applies the GTE predicate on the "claimed_at" field.
func ClaimedAtGTE(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldGTE(FieldClaimedAt, v))
}

// ClaimedAtLT applies the LT predicate on the "claimed_at" field.
func ClaimedAtLT(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldLT(FieldClaimedAt, v))
}

// ClaimedAtLTE applies the LTE predicate on the "claimed_at" field.
func ClaimedAtLTE(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldLTE(FieldClaimedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DailyCheckInClaim) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DailyCheckInClaim) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DailyCheckInClaim) predicate.DailyCheckInClaim {
	return predicate.DailyCheckInClaim(sql.NotPredicates(p))
}
