// Code generated by ent, DO NOT EDIT.

package webchatconversation

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the webchatconversation type in the database.
	Label = "web_chat_conversation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDefaultModel holds the string denoting the default_model field in the database.
	FieldDefaultModel = "default_model"
	// FieldDefaultProvider holds the string denoting the default_provider field in the database.
	FieldDefaultProvider = "default_provider"
	// FieldLastModel holds the string denoting the last_model field in the database.
	FieldLastModel = "last_model"
	// FieldLastProvider holds the string denoting the last_provider field in the database.
	FieldLastProvider = "last_provider"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMessageCount holds the string denoting the message_count field in the database.
	FieldMessageCount = "message_count"
	// FieldLastMessageAt holds the string denoting the last_message_at field in the database.
	FieldLastMessageAt = "last_message_at"
	// Table holds the table name of the webchatconversation in the database.
	Table = "web_chat_conversations"
)

// Columns holds all SQL columns for webchatconversation fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldTitle,
	FieldDefaultModel,
	FieldDefaultProvider,
	FieldLastModel,
	FieldLastProvider,
	FieldStatus,
	FieldMessageCount,
	FieldLastMessageAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTitle holds the default value on creation for the "title" field.
	DefaultTitle string
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultDefaultModel holds the default value on creation for the "default_model" field.
	DefaultDefaultModel string
	// DefaultModelValidator is a validator for the "default_model" field. It is called by the builders before save.
	DefaultModelValidator func(string) error
	// DefaultDefaultProvider holds the default value on creation for the "default_provider" field.
	DefaultDefaultProvider string
	// DefaultProviderValidator is a validator for the "default_provider" field. It is called by the builders before save.
	DefaultProviderValidator func(string) error
	// DefaultLastModel holds the default value on creation for the "last_model" field.
	DefaultLastModel string
	// LastModelValidator is a validator for the "last_model" field. It is called by the builders before save.
	LastModelValidator func(string) error
	// DefaultLastProvider holds the default value on creation for the "last_provider" field.
	DefaultLastProvider string
	// LastProviderValidator is a validator for the "last_provider" field. It is called by the builders before save.
	LastProviderValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultMessageCount holds the default value on creation for the "message_count" field.
	DefaultMessageCount int
)

// OrderOption defines the ordering options for the WebChatConversation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDefaultModel orders the results by the default_model field.
func ByDefaultModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultModel, opts...).ToFunc()
}

// ByDefaultProvider orders the results by the default_provider field.
func ByDefaultProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultProvider, opts...).ToFunc()
}

// ByLastModel orders the results by the last_model field.
func ByLastModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastModel, opts...).ToFunc()
}

// ByLastProvider orders the results by the last_provider field.
func ByLastProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastProvider, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMessageCount orders the results by the message_count field.
func ByMessageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessageCount, opts...).ToFunc()
}

// ByLastMessageAt orders the results by the last_message_at field.
func ByLastMessageAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMessageAt, opts...).ToFunc()
}
