// Code generated by ent, DO NOT EDIT.

package webchatmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// ConversationID applies equality check predicate on the "conversation_id" field. It's identical to ConversationIDEQ.
func ConversationID(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldConversationID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldUserID, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldRole, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldModel, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldProvider, v))
}

// ContentText applies equality check predicate on the "content_text" field. It's identical to ContentTextEQ.
func ContentText(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldContentText, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldStatus, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldErrorMessage, v))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldUsageLogID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLTE(FieldUpdatedAt, v))
}

// ConversationIDEQ applies the EQ predicate on the "conversation_id" field.
func ConversationIDEQ(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldConversationID, v))
}

// ConversationIDNEQ applies the NEQ predicate on the "conversation_id" field.
func ConversationIDNEQ(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNEQ(FieldConversationID, v))
}

// ConversationIDIn applies the In predicate on the "conversation_id" field.
func ConversationIDIn(vs ...int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldIn(FieldConversationID, vs...))
}

// ConversationIDNotIn applies the NotIn predicate on the "conversation_id" field.
func ConversationIDNotIn(vs ...int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNotIn(FieldConversationID, vs...))
}

// ConversationIDGT applies the GT predicate on the "conversation_id" field.
func ConversationIDGT(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGT(FieldConversationID, v))
}

// ConversationIDGTE applies the GTE predicate on the "conversation_id" field.
func ConversationIDGTE(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGTE(FieldConversationID, v))
}

// ConversationIDLT applies the LT predicate on the "conversation_id" field.
func ConversationIDLT(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLT(FieldConversationID, v))
}

// ConversationIDLTE applies the LTE predicate on the "conversation_id" field.
func ConversationIDLTE(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLTE(FieldConversationID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLTE(FieldUserID, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldContainsFold(FieldRole, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldContainsFold(FieldModel, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldContainsFold(FieldProvider, v))
}

// ContentTextEQ applies the EQ predicate on the "content_text" field.
func ContentTextEQ(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldContentText, v))
}

// ContentTextNEQ applies the NEQ predicate on the "content_text" field.
func ContentTextNEQ(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNEQ(FieldContentText, v))
}

// ContentTextIn applies the In predicate on the "content_text" field.
func ContentTextIn(vs ...string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldIn(FieldContentText, vs...))
}

// ContentTextNotIn applies the NotIn predicate on the "content_text" field.
func ContentTextNotIn(vs ...string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNotIn(FieldContentText, vs...))
}

// ContentTextGT applies the GT predicate on the "content_text" field.
func ContentTextGT(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGT(FieldContentText, v))
}

// ContentTextGTE applies the GTE predicate on the "content_text" field.
func ContentTextGTE(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGTE(FieldContentText, v))
}

// ContentTextLT applies the LT predicate on the "content_text" field.
func ContentTextLT(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLT(FieldContentText, v))
}

// ContentTextLTE applies the LTE predicate on the "content_text" field.
func ContentTextLTE(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLTE(FieldContentText, v))
}

// ContentTextContains applies the Contains predicate on the "content_text" field.
func ContentTextContains(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldContains(FieldContentText, v))
}

// ContentTextHasPrefix applies the HasPrefix predicate on the "content_text" field.
func ContentTextHasPrefix(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldHasPrefix(FieldContentText, v))
}

// ContentTextHasSuffix applies the HasSuffix predicate on the "content_text" field.
func ContentTextHasSuffix(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldHasSuffix(FieldContentText, v))
}

// ContentTextEqualFold applies the EqualFold predicate on the "content_text" field.
func ContentTextEqualFold(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEqualFold(FieldContentText, v))
}

// ContentTextContainsFold applies the ContainsFold predicate on the "content_text" field.
func ContentTextContainsFold(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldContainsFold(FieldContentText, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldContainsFold(FieldStatus, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldContainsFold(FieldErrorCode, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldContainsFold(FieldErrorMessage, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDGT applies the GT predicate on the "usage_log_id" field.
func UsageLogIDGT(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGT(FieldUsageLogID, v))
}

// UsageLogIDGTE applies the GTE predicate on the "usage_log_id" field.
func UsageLogIDGTE(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldGTE(FieldUsageLogID, v))
}

// UsageLogIDLT applies the LT predicate on the "usage_log_id" field.
func UsageLogIDLT(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLT(FieldUsageLogID, v))
}

// UsageLogIDLTE applies the LTE predicate on the "usage_log_id" field.
func UsageLogIDLTE(v int64) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldLTE(FieldUsageLogID, v))
}

// UsageLogIDIsNil applies the IsNil predicate on the "usage_log_id" field.
func UsageLogIDIsNil() predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldIsNull(FieldUsageLogID))
}

// UsageLogIDNotNil applies the NotNil predicate on the "usage_log_id" field.
func UsageLogIDNotNil() predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.FieldNotNull(FieldUsageLogID))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WebChatMessage) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WebChatMessage) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WebChatMessage) predicate.WebChatMessage {
	return predicate.WebChatMessage(sql.NotPredicates(p))
}
